### ISSUE TITLE
issue-summarization liveness probe causing failure

### ISSUE THREAD

**Issue by BenHall** [kubeflow/examples#106]
The `issue-summarization` app returns a 404 which causes the liveness probe to think the application has failed. 

Based on the docs - "Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure." (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request)

Here is an example:

```
$ docker run -d -p 5000:5000 gcr.io/kubeflow-images-public/issue-summarization:0.1
$ docker logs -f 2fcc527ea088cf67c2944f4220c49771378f29c081f8af483ef6b1cd57f0d117
Using TensorFlow backend. * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
$ curl localhost:5000 -i
HTTP/1.0 404 NOT FOUND
Content-Type: text/html
Content-Length: 233
Server: Werkzeug/0.14.1 Python/3.6.4
Date: Fri, 27 Apr 2018 12:57:48 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

//cc @jlewi

**Comment by jlewi** [comment]
@cliveseldon @ahousley We're using the Seldon server. Any idea how to deal with this?

One work around would be to disable the liveness probe at least for the infrastructure.
