### ISSUE TITLE
Feedback/issues trying out the github issue summarization example

### ISSUE THREAD

**Issue by leomzhong** [kubeflow/examples#111]
I tried the github issue summarization example (for the training step, only tried the notebook training), and just want to provide some feedback based on my experience. Some of them might due to that I am very new to Kubernetes/kubeflow.

**Potential Bugs**
- In the training notebook at the "Evaluate Model: BLEU Score" step -- I will send a patch to fix this.
> TypeError                                 Traceback (most recent call last) \<ipython-input-27-a5185bbfdb6f\> in \<module\>()
              3 bleu_score = seq2seq_inf.evaluate_model(holdout_bodies=testdf.body.tolist(), 
              4                                         holdout_titles=testdf.issue_title.tolist(),
----> 5                                         max_len_title=12)
TypeError: evaluate_model() got an unexpected keyword argument 'max_len_title'

- Cannot bring up the UI job following the instruction when running "ks apply ${KF_ENV} -c ui"

> ERROR find objects: RUNTIME ERROR: couldn't open import "download_data.sh": no match locally or in the Jsonnet library paths

I am using the pre-generated "ks-kubeflow" ksonnet app folder here, and I do see the 'download_data.sh' file under the components folder.

**Documentation Improvement**
I feel some of the documentation could be improved to make the experience more smooth
- In the setup instruction, create the persistent disk first before bringing up kubeflow-core. This should help avoid having to restart the 'tf-hub' pod after deploying kubeflow

- For the "Bringing up a Notebook" step, give an explicit suggestion on how much memory the notebook needs. I was using 2Gi (suggested as a "good starting points"), but the notebook keep restarting during the training (I think it is due to OOM, but the log is not helpful. I modified the training batch to 600 instead of 1200 and everything works OK)

- It would be great if we can make it clear for each step whether we are under the ksonnet app we created, or under the github repo we cloned locally.

**Comment by oskar-j** [comment]
Unfortunately, seems like there are still issues for the `github_issue_summarization` project. I'm new to the kubeflow framework so I tried to follow the tutorial - https://github.com/kubeflow/examples/tree/master/github_issue_summarization -  I'm stuck at the point no. 2 called "Training the model using a Jupyter Notebook". Pardon if I forgot some crucial step in the meantime :smile: 

### **Errors in code**

#### Batch size

From `Training.ipynb`:

```
batch_size = 1200
epochs = 7
history = seq2seq_Model.fit([encoder_input_data, decoder_input_data], np.expand_dims(decoder_target_data, -1),
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.12, callbacks=[csv_logger, model_checkpoint])
```

training network causes Python kernel crash (same situation found by @leomzhong)

I changed the batch_size to make it work

`batch_size = 120`

#### Not complete requirements.txt

It's unclear whether to use https://github.com/kubeflow/examples/blob/master/github_issue_summarization/requirements.txt or https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/requirements.txt for the *Jupyter part*.

https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/requirements.txt should also have `pydot` as it's directly used by the Jupyter notebook.

#### Exporting trained model files

There is a kubectl command 

```
PODNAME=`kubectl get pods --namespace=${NAMESPACE} --selector="app=jupyterhub" --output=template --template="{{with index .items 0}}{{.metadata.name}}{{end}}"`
``` 
in https://github.com/kubeflow/examples/blob/master/github_issue_summarization/02_training_the_model.md , which fails in my environment

```
oskar@ubuntu:~/Notebooks/examples/github_issue_summarization/notebooks$ PODNAME=`kubectl get pods --namespace=${NAMESPACE} --selector="app=jupyterhub" --output=template --template="{{with index .items 0}}{{.metadata.name}}{{end}}"`
error: error executing template "{{with index .items 0}}{{.metadata.name}}{{end}}": template: output:1:7: executing "output" at <index .items 0>: error calling index: index out of range: 0
```

**Comment by jlewi** [comment]
Thanks for the feedback.
