### ISSUE TITLE
Replace YAML portions of the mnist Argo workflow with ksonnet commands

### ISSUE THREAD

**Issue by elsonrodriguez** [kubeflow/examples#113]
As the kubeflow ksonnet code gains s3 support, replace the YAML in the argo workflow with `ks` commands.

This will also allow for the addition of a manual guide, which will let the user interact more directly with kubeflow.

With https://github.com/kubeflow/kubeflow/pull/710 merged Tensorboard can be swapped out. This leaves model training itself.

**Comment by texasmichelle** [comment]
Do you want to update this to use kustomize or close?

**Comment by elsonrodriguez** [comment]
Let's close it out, I think the mnist example might need an entire refactor at this point.
