### ISSUE TITLE
[GH Issue Summarization] Create a ksonnet app

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/examples#13]
Create a ksonnet app for deploying the model & web app.

Component of #14.

**Comment by texasmichelle** [comment]
Are we documenting how a user creates this or actually committing the generated files? @jlewi @ankushagarwal @vicaire

**Comment by ankushagarwal** [comment]
I think that we should just document how users create the ksonnet app by pointing them to the user guide. Since we plan to have multiple examples in this repo, we would essentially be duplicating all of those ksonnet files. Another challenge would be keeping them in sync with changes to kubeflow.

**Comment by texasmichelle** [comment]
That makes sense.
