### ISSUE TITLE
[code_search] Create a Kubeflow cluster in kubeflow-dev

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#132]
We'd like to setup a Kubeflow dev cluster for use in the code_search example.

We should create a separate cluster from dev.kubeflow.org so that we don't experience the churn of updating dev.kubeflow.org

/assign @activatedgeek 
/cc @hamelsmu

**Comment by activatedgeek** [comment]
The cluster is available at `code-search.endpoints.kubeflow-dev.cloud.goog` for now. Bringing up a  fresh cluster takes ~10mins (with a major chunk during the first time taken by HTTPS certificate deployment) so any modifications can be easily done.

**Comment by activatedgeek** [comment]
This issues was blocked on some bugs and has now been fixed. /close

**Comment by activatedgeek** [comment]
This issues was blocked on some bugs and has now been fixed.
/close
