### ISSUE TITLE
[code_search] Script to load model metrics into Katib/ModelDB

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#134]
We'd like to take advantage of Katib's integration with model db. To track the performance of models.
More detail can be found in the [doc](https://docs.google.com/document/d/1lqXmL_32cmDQ8z7MSl3FJ6p45RF-KDw5isGLyxPXsa8/edit#heading=h.wnld1hwmjum9).

The first step is probably a simple script that can load relevant data about a model into Katib. The data we probably want is

 * GCS location of the model
 * Evaluation metrics for the model

**Comment by jlewi** [comment]
Here are some instructions on how to use ModelDB for this.
https://github.com/mitdbg/modeldb/blob/master/client/python/light_api.md

I looked at the Katib CLI but I'm not sure the Katib CLI is that useful in this case.

**Comment by jlewi** [comment]
I used the ModelDB sample code to create a model and store data in ModelDB
https://github.com/jlewi/kubeflow-dev/tree/master/modeldb

This appears to have worked

  * In the projects UI tab I can see the newly created project and it lists two models
  * It also shows some statistics that lead me to believe the data was actually loaded

![projects](https://user-images.githubusercontent.com/777219/42129694-19048a02-7c81-11e8-8182-acae9340257f.png)

But when I click on the projects tab I just get a screen that says loading models

![loading_models](https://user-images.githubusercontent.com/777219/42129696-34763e7a-7c81-11e8-8044-f53c67b57242.png)

@mpvartak Any thoughts? 

I'd like to be able to use ModelDB to store metadata about a model e.g.

  * Location of a model 
  * Data used to train
  * Various metrics and parameters

And then be able to use ModelDB's UI to browse the models.

**Comment by mpvartak** [comment]
@jlewi this is the same workflow that's being used in Katib afaik. So that should work the same. I will try to repro the bug and ping back here.

**Comment by jlewi** [comment]
Thanks.

**Comment by jlewi** [comment]
@mpvartak What do you mean by setup? I'm running on GKE using Katib so I assume the setup is different (possibly different versions of modeldb from what is running in modeldb).

I copied the code from https://github.com/mitdbg/modeldb/blob/master/client/python/light_api.md so I expect its the same.

Can you provide suggestions on how to debug this?

Is there a way to query the database directly e.g. through an API or a CLI so I can see whether the data is there and whether its just a UI issue?

**Comment by mpvartak** [comment]
Here's my setup: pip install modeldb + the docker versions of the frontend and backend. I'm on Python2.7. I use the same code as the on the webpage (Method 2 specifically) and am able to log models/visualize correctly. So I can confirm that works. I haven't tried on GKE, so can't comment on what might be going on there.

For debugging, the sqlite file lives in server/codegen/sqlite and can be read directly using sqlite3; you can query the mongo data via mongod. I'd recommend making sure that the sqlite DB shows the models in FitEvent table + ExperimentRun tables. If that looks good, then next step is to check on the key-value data stored in mongodb.

**Comment by bhack** [comment]
When we talk about GCS, i.e. for the location of the model, can we use a more generic approach like https://github.com/GoogleContainerTools/kaniko/issues/121#issuecomment-382573584?

**Comment by jlewi** [comment]
@mpvartak Can you provide your syncer config and a link to your python code?

**Comment by jlewi** [comment]
@mpvartak I can see data in the sqllite DB but I'm not sure what I'm looking for. Would you be willing to try it out on our dev cluster (dev.kubeflow.org)? I'd be happy to give you access; I just need a Google account for you.

**Comment by jlewi** [comment]
It looks like Katib added an API to upload model data; see 
kubeflow/katib#43

I don't think there's a CLI yet; but we might have more luck with Katib.

**Comment by lluunn** [comment]
cc @lluunn

**Comment by mpvartak** [comment]
Hey @jlewi @garganubhav my team is rewriting the guts of modeldb to make it more robust, add features, and make easy to deploy on kubernetes. let me share the roadmap and get the kubeflow team's feedback too. on slack, is katib the best channel to have this discussion?

i'm happy to help @garganubhav on this issue, let's figure out if it makes sense to integrate into current modeldb or can wait for next version.

**Comment by garganubhav** [comment]
@jlewi yes, would update very soon. @mpvartak thank you, the channel on slack is model-management

**Comment by chrisheecho** [comment]
Hi @garganubhav do you have any update on this one? we are trying to cut down issues on 0.4 and would love to get your take

**Comment by mpvartak** [comment]
I have a solution for the persistence issue. Let me push to MDB repo.

**Comment by garganubhav** [comment]
@chrisheecho this is tested. Modeldb is working with Katib.

**Comment by jlewi** [comment]
@garganubhav So do we have a script and docs somewhere that we can point customers to? What is the remaining work to close this out?

**Comment by garganubhav** [comment]
As I know, ModelDb is currently deleted from Katib.

**Comment by jlewi** [comment]
@garganubhav @mpvartak has a PR open to add modeldb as a separate package. So it would still be good to have examples and instructions for how people can take advantage of modeldb to track their models.

**Comment by garganubhav** [comment]
Yes, I was checking it before and was getting some error. Will try today again.
