### ISSUE TITLE
[GH Issue Summarization] E2E Solution on Kubeflow

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/examples#14]
_Replicated from [Kubeflow #157](https://github.com/kubeflow/kubeflow/issues/157)._

@hamelsmu published a great [blog post](https://hackernoon.com/how-to-create-data-products-that-are-magical-using-sequence-to-sequence-models-703f86a231f8) about using sequence to sequence models to summarize GitHub issues.

It would be great to turn this into an E2E solution using Kubeflow that highlights the benefit of using Kubeflow and K8s for data science.

There are lots of reasons why I think this blog post would make for a fantastic E2E solution
- Text summarization has a lot of applications
- It uses GitHub data which is a very rich dataset
- Training and preprocessing take enough time (~30 minutes and ~1 hour respectively) that I think it makes sense to run these as K8s jobs but not so much time to be a barrier.

Here's a stab at what an E2E solution might look like
- Entrypoint would be a notebook (based on the [one in the blogpost](https://github.com/hamelsmu/Seq2Seq_Tutorial/blob/master/notebooks/Tutorial.ipynb)).
- Notebook would walk through the various steps but instead of (or in addition) to running code directly in the notebook.

I think there's quite a bit of work to be done but I think we can split this into tasks
- [X]  Setup a shared Kubeflow cluster and Cloud project for dev team to use
- [x]  Create a Docker image to be used with Jupyter with all dependencies installed
- [x]  ~~Refactor the notebook into libraries with suitable main functions so that relevant steps (preprocessing and training) steps can be invoked in K8s Jobs and TFJobs~~
- [x]  Build docker image (using [Argo](https://applatix.com/open-source/argo/) to be used by TFJob, TFServing, etc...
- [x]  Create a model server using ~~TFServing~~ Seldon core
- [x]  Create a web app to serve as the front end
- [x]  Create ksonnet component for deploy the model and web app

**Comment by ankushagarwal** [comment]
I'm working on this. Should have most of these done by end of this week.

**Comment by texasmichelle** [comment]
Great! Are there specific pieces that you'd like me to pick up?

**Comment by hamelsmu** [comment]
Please let me know if you have any questions on the modeling or data transformation pieces, I'm happy to help.

**Comment by texasmichelle** [comment]
Basic solution in place. Additional issues have been created with prioritization for further improvements (#37, #39, #40, #43).
