### ISSUE TITLE
[code_search] Log clicks

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#140]
We will want to modify the front end web app to log clicks.

See [here](https://docs.google.com/document/d/1lqXmL_32cmDQ8z7MSl3FJ6p45RF-KDw5isGLyxPXsa8/edit#heading=h.bxgg4ip1zx3a)

This is blocked on an initial web app (#135)

**Comment by Akado2009** [comment]
Greetings!

Can I try this?
