### ISSUE TITLE
[GPU Serving] Serving example with GPUs? Inception?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#145]
There's lots of interest in serving with GPUs but we don't have a good example showing how to do this.

I think it would be nice to have one. 

A simple example might be inception with a simple front end that allows people to upload images for classification.

**Comment by jlewi** [comment]
There's a pretty comprehensive tutorial here
https://github.com/google-aai/tf-serving-k8s-tutorial

Maybe we can just link to that or modify it to work with Kubeflow?

**Comment by jlewi** [comment]
This [blog](https://cloud.google.com/blog/big-data/2017/09/performing-prediction-with-tensorflow-object-detection-models-on-google-cloud-machine-learning-engine) is a pretty good model.

It would be nice to make the following changes

- Create a web app to surface the results rather than just using a notebook
- Use GPUs for serving.

**Comment by cliveseldon** [comment]
Using Seldon to serve should be straight forward as adding the requires resource requests for GPU resources in our CustomResource assuming you have set up the cluster to allow them. 

As you can use any Dockerized solution with Seldon you are free to compile your model with TensorRT or other frameworks.

**Comment by jklaise** [comment]
> This blog is a pretty good model.
> 
> It would be nice to make the following changes
> 
> Create a web app to surface the results rather than just using a notebook
> Use GPUs for serving.

@jlewi I'm working on implementing this example with serving done by Seldon including the training on GCP part as covered [https://cloud.google.com/blog/big-data/2017/06/training-an-object-detector-using-cloud-machine-learning-engine](here). Currently having issues getting the training part working, think it might be a Tensorflow version issue.

**Comment by jlewi** [comment]
@jklaise cool. Are you planning on using TFServing with Seldon?

**Comment by jklaise** [comment]
@jlewi No we don't, the plan is to provide an example to export a GCP trained model to a format that can easily be dockerized for serving with Seldon.

**Comment by cliveseldon** [comment]
The plan is to try and use that example blog to train the model and export to run on seldon. Once done, I assume we can work with you to train on kubeflow directly and finally deploy with GPUs on an appropriate cluster to get a good e2e example?

**Comment by jlewi** [comment]
@lluunn We now have a GPU serving example right?

**Comment by lluunn** [comment]
Yes.
I can't close issue in examples repo.
