### ISSUE TITLE
Create XGBoost Zillow housing prediction example from Kaggle kernel

### ISSUE THREAD

**Issue by puneith** [kubeflow/examples#16]
Create XGBoost Zillow housing prediction example from [Kaggle Zestimate kernel](https://www.kaggle.com/c/zillow-prize-1/kernels).

**Comment by jlewi** [comment]
Adding this to our 0.2 release because we will want an XGBoost example.

**Comment by jlewi** [comment]
@puneith Any update?

**Comment by puneith** [comment]
Only update is that I am now actively working on this and more focused on codelab piece (the Github code should also be delivered as part of it but that has to be seen). In the meantime I have run into a data license issue for Zestimate (Data not allowed outside competition). Kaggle legal is verifying it an exception can be made and if not then I will find some other dataset for XGBoost.

**Comment by jlewi** [comment]
@puneith #27 is in review and almost done. I believe the decision was to switch the dataset to the Ames dataset for licensing reasons?

**Comment by puneith** [comment]
@jlewi correct!

**Comment by jlewi** [comment]
@puneith Can we close this issue?
