### ISSUE TITLE
[GH Issue Summarization] Add setup steps

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/examples#172]
We currently require a k8s cluster and ksonnet installation, but it could be useful to have an example of how to set those up, pinned to a specific version:

- [ ] Installing ksonnet
```
export KS_VER=ks_0.11.0_linux_amd64
wget -O /tmp/$KS_VER.tar.gz https://github.com/ksonnet/ksonnet/releases/download/v0.11.0/$KS_VER.tar.gz
mkdir -p ${HOME}/bin
tar -xvf /tmp/$KS_VER.tar.gz -C ${HOME}/bin
export PATH=$PATH:${HOME}/bin/$KS_VER
```
- [ ] Creating a managed cluster: 
```
gcloud container clusters create kubeflow-examples-cluster
```
- [ ] Alternatively, add a link to a codelab or somewhere that describes the process well.

**Comment by Akado2009** [comment]
@texasmichelle 
Greetings, can I take it?
