### ISSUE TITLE
[GH Issue Summarization] Training improvements

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/examples#174]
- [ ] Improve clarity around different training options (notebook vs tf-job vs t2t). The main page should call them out as 3 different ways to accomplish similar things and links at the bottom of each training option should clearly reference the other options as alternates
- [ ] Improve clarity around different storage options (PV vs GCS)
- [ ] Update tf-job with instructions for using the most recent version of kubeflow (tfjob-v1alpha2?)

**Comment by hackintoshrao** [comment]
Would like to take this if this is not yet fixed. Also would like to add Minio as a storage option if it doesn't exist for the example.

**Comment by jlewi** [comment]
@hackintoshrao Yes please; are you still interested in working on this?

**Comment by hackintoshrao** [comment]
Hello @jlewi , absolutely yes.

**Comment by jlewi** [comment]
@hackintoshrao My suggestion would be to go through the markdown docs in this directory:
https://github.com/kubeflow/examples/tree/master/github_issue_summarization

and try to follow the instructions and then report and potentially fix any issues you run into.

In particular here are some changes to look out for

* We have deleted the T2T jobs so we should remove any reference to them in the docs.
* We should only be using TFJob v1alpha2 and we can remove all references to v1alpha1

**Comment by hackintoshrao** [comment]
Thanks @jlewi for your time, these would be good starting points.

**Comment by hackintoshrao** [comment]
@jlewi , Found some issues and have sent a PR https://github.com/kubeflow/examples/pull/403 .
