### ISSUE TITLE
[Object Detection] Parameterize the K8s objects

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#178]
The object detection example has a bunch of YAML manifests; e.g.
https://github.com/kubeflow/examples/blob/master/object_detection/jobs/pets-training.yaml

Can we turn these manifests into a ksonnet application and parameterize them so its easy for users to change things like the docker image, input/output location.

I believe ksonnet supports YAML now so we might not even need to convert the manifests to jsonnet.

**Comment by ldcastell** [comment]
Hi @jlewi, sure I will start looking into it :)

**Comment by jlewi** [comment]
The YAML functionality in ksonnet doesn't appear to be well documented.

I've had some success doing 

```
ks import -f path/to/yaml
```

I haven't figured out how to substitute parameters to YAML manifests. 

I have a question out to the ksonnet folks ksonnet/ksonnet#782

**Comment by ldcastell** [comment]
@jlewi would it be something like this:
```
ks param set component metadata.name newname
```
