### ISSUE TITLE
[GH Issue Summarization] Fix tfjob training

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/examples#186]
When following the instructions in [Training the model with TFJob](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/02_training_the_model_tfjob.md), generated model files result in nonsense predictions.

Example: for [this URL](https://github.com/ksonnet/ksonnet/issues/726), the generated summary is:
“star following light template nearby offset bot attached informations gh gh market”

In previous iterations (`gcr.io/kubeflow-images-public/issue-summarization:0.1`) predictions are much better:
“init failed on mac os”

Figure out whether the trained model files are being exported properly and added to the image. I suspect something in [notebooks/train.py](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/train.py) is responsible.

**Comment by jlewi** [comment]
We should also think about which model/code we want to use; 
Right now we have two

1. notebooks/train.py - I think this is the original Keras code
1. The TF.Estimator model added in #203 

The Keras model doesn't produce TensorBoard output as far as I can tell.
But currently our serving story using Seldon is for the Keras model.

If we switch to using TF.estimator; we can hopefully just serve it using TF.Serving. Although its possible that doesn't take care of preprocessing.

**Comment by jlewi** [comment]
I don't think [train.py](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/train.py) is actually training the model

I think its missing a call to model fit e.g. if you look at the notebook we do 

```
script_name_base = 'tutorial_seq2seq'
csv_logger = CSVLogger('{:}.log'.format(script_name_base))
model_checkpoint = ModelCheckpoint('{:}.epoch{{epoch:02d}}-val{{val_loss:.5f}}.hdf5'.format(script_name_base),
                                   save_best_only=True)

batch_size = 1200
epochs = 7
history = seq2seq_Model.fit([encoder_input_data, decoder_input_data], np.expand_dims(decoder_target_data, -1),
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.12, callbacks=[csv_logger, model_checkpoint])
```

**Comment by jlewi** [comment]
There are 3 versions of the code

* [Training.ipynb](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/Training.ipynb)
* [train.py](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/train.py)
* [distributed/train.py](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/distributed/train.py)

There's really no reason to have train.py and distributed/train.py.

Here are the primary differences

* distributed/train.py is using TF.estimator ; train.py doesn't
* train.py has support for downloading/uploading files to GCS
* distributed/train.py is using tensorflow.keras vs native tensorflow

Using TF.Estimator doesn't work see discussion in #265 (we are hitting keras-team/keras#/9761).

In #265 I refactored the code so we can train either using Keras' fit or TF.Estimator. 

So if we add support for reading/writing from GCS and making the command line arguments match train.py; then we should be able to replace train.py with distributed/train.py

In #265 I also wrote the code in such a way that we should be able to reuse it in the notebook, so we could eiiminate duplication with train.ipynb

**Comment by netankit** [comment]
@jlewi  Following this "Need = P0, Want = P1, Punt = P2". 
But, thanks for clarifying on the call. Just felt this was a Need as this example is something most people have gravitated first to get started.

**Comment by chrisheecho** [comment]
sounds like P1 to me!

**Comment by jlewi** [comment]
TFJob should be fixed. I think the only remaining work would be to train a model and test the quality of the predictions.

**Comment by jlewi** [comment]
Should we punt to 0.5?
Anyone working on actually training and testing the quality of the model?
