### ISSUE TITLE
[gh_issue_summarization] distributed training using Keras

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#196]
When we previously tried using distributed training with the Keras Seq2Seq model (#43)

We ran into the error in this [comment](https://github.com/kubeflow/examples/issues/43#issuecomment-380633578)

```
InvalidArgumentError (see above for traceback): Cannot colocate nodes 'Decoder-Word-Embedding/embeddings' and 'training/Nadam/gradients/Decoder-Word-Embedding/Gather_grad/Shape: Cannot merge devices with incompatible jobs: '/job:worker/task:0' and '/job:ps/task:0'
   [[Node: Decoder-Word-Embedding/embeddings = VariableV2[container="", dtype=DT_FLOAT, shape=[4278,300], shared_name="", _device="/job:ps/task:0"]()]]
```

using this code
https://gist.github.com/ankushagarwal/a2dab3aaf664a4296292c4ff330fb5e6

This is supposedly fixed with TensorFlow 1.9 and tf.Keras.

This would be worth retrying to see if we can make distributed training work with the Keras model.

**Comment by inc0** [comment]
@jlewi yeah. My best bet is to use tf.keras.model_to_estimator and enable https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distribute/python/multi_worker_strategy.py - distributed strategy that would take ClusterSpec as input and be capable of data-parallel distribute training. That, if I'm correct, would allow us to write boilerplate code that would enable any tf.keras model to be trained with tf-job.

**Comment by jlewi** [comment]
#203 doesn't appear to properly train a model so reopening this bug.

If you look at the original PR there was a fix me
https://github.com/kubeflow/examples/pull/203/files#diff-400db61475ce06583dc398d366335851R143

Indicating that the code is hitting:
https://github.com/keras-team/keras/issues/9761

#203 seems to have worked around that by dropping a layer and thus computing non-sensical predications.

#265 attempt to fix that by matching the original code in terms of layer construction. #265 includes a test which reproduces the error.
https://github.com/kubeflow/examples/pull/265#issuecomment-431830632

In #265 we tried to train a valid model using Keras' fit function but that turns out to have problems (#280) if we use the Keras that ships with TF.

So in #265 we reverted to not using the Keras that ships with TF so that we could train a model.

**Comment by amygdala** [comment]
Just a note that model_to_estimator() doesn't work b/c of passing encoder state to the decoder initial_state (that is, it doesn't work b/c initial_state is set). 
I believe the underlying issue is that such a model isn't guaranteed to be serializable.
