### ISSUE TITLE
Create E2E example of distributed model training and serving.

### ISSUE THREAD

**Issue by elsonrodriguez** [kubeflow/examples#2]
Currently most of the examples do not show how to complete the training of a model within kubeflow, and also take that trained model and serve it with kubeflow.

We need an example that covers this from start to finish.

**Comment by elsonrodriguez** [comment]
Working on this, can someone assign?

**Comment by jlewi** [comment]
This is fantastic. What dataset problem are you trying to solve?

**Comment by jlewi** [comment]
@elsonrodriguez Ping?

**Comment by elsonrodriguez** [comment]
We're trying to narrow down what model/data combo can be fully trained within a reasonable timeframe. 

Any suggestions?

**Comment by texasmichelle** [comment]
@elsonrodriguez I'm beginning work on [Kubeflow #157](https://github.com/kubeflow/kubeflow/issues/157). Want to help? I broke it down into pieces as issues in this repo, so feel free to pick one of them up.

**Comment by elsonrodriguez** [comment]
@texasmichelle Yeah Sure! We ended up going with mnist and are just about done with an initial pass on this. I'll ping you when I open the PR and if you see anything that can be re-used let me know and I'll try to make it more generic to fit the GH summarization use case.
