### ISSUE TITLE
[codelab-e2e-gis-feedback]: missing cd command in Training Image section

### ISSUE THREAD

**Issue by WyattGorman** [kubeflow/examples#218]
In the "(Optional) Create the training image" section, users run "cd ${HOME}/examples/github_issue_summarization/notebooks", and later run "ks param set --env gke tfjob-v1alpha2 image "gcr.io/${PROJECT_ID}/tf-job-issue-summarization:${TAG}"", however that ks command needs to be run from "${HOME}/examples/github_issue_summarization/ksonnet-kubeflow". 

I'd propose adding a "cd ${HOME}/examples/github_issue_summarization/ksonnet-kubeflow" command before the ks command above.

**Comment by texasmichelle** [comment]
Thanks! Fixed
