### ISSUE TITLE
[codelab-e2e-gis-feedback]: Destroy the Cluster command missing zone/region

### ISSUE THREAD

**Issue by WyattGorman** [kubeflow/examples#219]
The "gcloud container clusters delete kubeflow-codelab" command in the "Destroy the Cluster" section requires a --zone or --region flag.

I'd propose changing "gcloud container clusters delete kubeflow-codelab" to "gcloud container clusters delete kubeflow-codelab --zone us-central1-a".

**Comment by texasmichelle** [comment]
Good catch, thanks for submitting.
