### ISSUE TITLE
gh-demo.kubeflow.org returns 404

### ISSUE THREAD

**Issue by BenHall** [kubeflow/examples#249]
Is http://gh-demo.kubeflow.org/ still being used for a demo? Currently returning a 404 and wondering if we should remove the link from our scenarios.

Ben

**Comment by texasmichelle** [comment]
I think we intended to keep that site alive. @ankushagarwal do you know where this is being hosted?

**Comment by ankushagarwal** [comment]
It was running in a k8s cluster in the `kubeflow-dev` GCP project. I don't see that cluster anymore. Looks like someone unintentionally deleted it.

**Comment by texasmichelle** [comment]
Is it straightforward enough to rebuild?

**Comment by ankushagarwal** [comment]
It's been a while since I've touched that. Should take half a day to rebuild and deploy everything.

**Comment by jlewi** [comment]
@BenHall I might suggest removing the link for now. We'll try to get it back up but I'm not sure when we'll have the cycles to do so.

**Comment by jlewi** [comment]
The ksonnet app is currently pointing to

```
NAME    OVERRIDE KUBERNETES-VERSION NAMESPACE SERVER
====    ======== ================== ========= ======
default          v1.7.0             kubeflow  https://35.188.73.10
```

This corresponds to

project: kubeflow-dev
cluster: dev-cluster

**Comment by jlewi** [comment]
This is a very old cluster and it looks like the kubeflow namespace is being deleted.

```
kubectl get namespace
NAME              STATUS        AGE
chasm             Active        121d
cloud-endpoints   Active        177d
default           Active        189d
gcp-deploy        Active        76d
istio-system      Active        175d
jlewi             Active        165d
katib             Active        113d
kube-public       Active        189d
kube-system       Active        189d
kubeflow          Terminating   189d
kubeflowtfgpu     Active        168d
test              Active        132d

```

**Comment by jlewi** [comment]
Should be back up at

gh-demo.kubeflow.org

I moved it into a new project
kubecon-gh-demo-1
and PR #261 should make it easier to deploy and update in the future.
