### ISSUE TITLE
[code_search] use spacy to tokenize the search queries

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#257]
During preprocessing we tokenize the docstrings using the spacy library.
https://github.com/kubeflow/examples/blob/2064b43deffa436fdf148edc2d4e67ee1580839a/code_search/src/code_search/dataflow/utils.py#L7

It doesn't look like we tokenize the search query at serving time
https://github.com/kubeflow/examples/blob/2064b43deffa436fdf148edc2d4e67ee1580839a/code_search/src/code_search/nmslib/search_engine.py#L27

Here's where we construct the encoders
https://github.com/kubeflow/examples/blob/master/code_search/src/code_search/nmslib/cli/start_search_server.py#L56

It looks like the query encode function is just calling the T2T encode function;
https://github.com/kubeflow/examples/blob/2064b43deffa436fdf148edc2d4e67ee1580839a/code_search/src/code_search/t2t/query.py#L4

Should we be tokenizing the query using spacy before we call encode?

@activatedgeek thoughts?

**Comment by activatedgeek** [comment]
That's a great point. However, it appears that the encoder that I am using from T2T model only takes in a string (and returns a list of integers values). See [here](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/text_encoder.py#L308).

I think that using `spacy` for tokenization only helps in situations where the input query has more complicated tokenizations. For simple input queries, we might as well be good enough using `<SPACE>` as the delimiter.

We could using `spacy` to separate things like `i want this. then this.` to `i want this<SPACE>. then this<SPACE>.` (the added spaces)

**Comment by jlewi** [comment]
Does spacy drop things like punctuation? Or perform other transformations?

> However, it appears that the encoder that I am using from T2T model only takes in a string (and returns a list of integers values). See here.

Can we just run spacy and then join the output with a space before passing to T2T?

**Comment by activatedgeek** [comment]
> Does spacy drop things like punctuation? Or perform other transformations?

I think it doesn't given that its sole purpose is to identify tokens in a grammar.

> Can we just run spacy and then join the output with a space before passing to T2T?

Yes, that is a possibility at the risk of introducing `<UNK>` (unknown) tokens in the input vector.
