### ISSUE TITLE
[code_search] Unittest for similarity and loss computation using TF.Eager 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#258]
Here:
https://github.com/kubeflow/examples/blob/2064b43deffa436fdf148edc2d4e67ee1580839a/code_search/src/code_search/t2t/similarity_transformer.py#L32

We construct a simple network to compute the loss for the query and code embeddings.

We can pull that code out into a class method and then write a unittest for it using TF.eager

**Comment by cwbeitel** [comment]
Here's a starting point:
