### ISSUE TITLE
[code_search] Fix model export for computing code embeddings

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#260]
Right now I think we are using the same T2T exported model for computing the code embeddings and the function embeddings.

But I think T2T exporter will create an exported model that outputs whatever the body function returns as outputs (see [T2T docs](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/t2t_model.py#L67))

Our body function is returning the query/docstring embeddings 
https://github.com/kubeflow/examples/blob/master/code_search/src/code_search/t2t/similarity_transformer.py#L52

Does #233 partially address this by adding a conditional variable to control which embeddings to return?

/cc @activatedgeek @cwbeitel

**Comment by jlewi** [comment]
It looks like in an email thread @rsepassi suggested adding a tf.cond to the graph and then including that in the features dict to use the right graph for inference. Which is what I think #233 is doing.

**Comment by cwbeitel** [comment]
Hmm I'm not sure the tf.cond is necessary but maybe I'm misunderstanding. You should just be able to have an infer method used like `self.infer(mode="code_embedding")` or `self.infer(mode="string_embedding")` that, depending on the mode, either calls self.encode with the string_embedding or code_embedding variable scope, thereby using use appropriate set of variables for the two encoder variants. In the infer function I think you would need to call self.bottom before calling self.encode (the former which has been called prior to self.body being called)?

Or is there something with t2t exporter that I'm not understanding like it assuming model(features) will be called directly?

**Comment by jlewi** [comment]
@cwbeitel Is is it possible to specify mode when using t2t_exporter to export the model?

**Comment by cwbeitel** [comment]
As discussed here's a starting point for testing training, exporting, and querying the model server e2e so we can verify everything is fitting together: https://github.com/cwbeitel/tk/blob/master/tk/models/similarity_transformer_export_test.py

As well as a thoughts on how we could refactor SimilarityTransformer to be more modular making it easier to use for inference and in testing https://github.com/cwbeitel/tk/blob/master/tk/models/similarity_transformer.py as well as how to toggle between different losses if we want to explore various.

**Comment by cwbeitel** [comment]
As well as a [starting point](https://github.com/cwbeitel/tk/blob/master/tk/models/similarity_transformer_test.py) for some basic tf.Eager tests you were suggesting in https://github.com/kubeflow/examples/issues/258

**Comment by cwbeitel** [comment]
To summarize our discussion we discussed exporting a single model that will compute both doc and code embeddings and return a single result with the computed embeddings concatenated. This is in the interest of having a short-term (at least) fix and trades extra computation for simplicity. This is reasonable because we aren't currently blocked by embedding computation time which would be more relevant when running this at large scale.
