### ISSUE TITLE
[GH Issue Summarization] Keras model doesn't work with keras in TensorFlow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#280]
#203 Introduced a new version of the train.py code that uses tensorflow.keras rather than the independent  keras module. This was intended to support distributed training using TF.Estimator.

The TF.Estimator code didn't work; it looks like we are hitting keras-team/keras#976

In #265 we wanted to eliminate the code duplication between train.py and distributed/train.py. So we created a single model with options to train using Keras' fit function or TF.Estimator.

Unfortunately using Keras' fit function doesn't work with tensorflow.keras.

This looks like a potential versioning issue.

It looks like the version of Keras that ships with TF 1.11 is 2.1.6. Keras is currently on 2.2 and various issues indicate breaking changes 

https://stackoverflow.com/questions/51181754/keras-tensorflow-convlstm2d-object-has-no-attribute-outbound-nodes
https://stackoverflow.com/questions/51515929/attributeerror-tensor-object-has-no-attribute-keras-shape-when-creating-a?rq=1

To get a model that works we can use Keras 2.2. Unfortunately, it loos like that doesn't include TF.Estimator. I think we need to switch to tensorflow.keras to get TF.estimator.

Opening this issue to track this. Ideally, the next version of tensorflow.keras will have a sufficiently new version of keras.

**Comment by amygdala** [comment]
re: "Unfortunately using Keras' fit function doesn't work with tensorflow.keras." -- this works for me.  I had to change some import statements to get it to work though... both in in the main script and in the utilities script.
(Also: I'm using tf 1.12 -- but I think the key was the imports).

**Comment by amygdala** [comment]
Happily, that means that at least we can use Keras' new ability to export in SavedModel format, and so use the trained model with tf-serving.

**Comment by Oblynx** [comment]
> The TF.Estimator code didn't work; it looks like we are hitting [keras-team/keras#976](https://github.com/keras-team/keras/issues/976)

I think you mean https://github.com/keras-team/keras/issues/9761

**Comment by Oblynx** [comment]
Hey @amygdala, what exactly did you change to make it work? Maybe a small PR?
