### ISSUE TITLE
[code_search] GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by connected-bsamadi** [kubeflow/examples#284]
I'm running the code_search example on Kubeflow 0.2.7 on GKE. I was wondering where GOOGLE_APPLICATION_CREDENTIALS is defined. I get this error:
```ERROR: (gcloud.auth.activate-service-account) Unable to read file []: [Errno 2] No such file or directory: ''```

Do you I need to do define it myself? Is this because I use Kubeflow 0.2.7?

**Comment by jlewi** [comment]
Are you running the notebook? 

You might need 0.3 in order to get the GCP secret to be automatically mounted in the container.

**Comment by jlewi** [comment]
@connected-bsamadi Did you get this resolved?

**Comment by connected-bsamadi** [comment]
I tried it with Kubeflow 0.3 and it works fine. To deploy Kubflow 0.2, I had used the following script. However, I just noticed these are, I think, out-dated. I just found the new instructions here:
https://v0-2.kubeflow.org/docs/started/getting-started-gke/

```
gcloud config set project $PROJECT_ID

# create a cluster
gcloud container clusters create kubeflow-codelab \
      --zone $ZONE --machine-type n1-standard-2

gcloud container clusters get-credentials kubeflow-codelab --zone $ZONE

kubectl create clusterrolebinding default-admin \
      --clusterrole=cluster-admin --user=$(gcloud config get-value account)

ks init ksonnet-kubeflow
cd ksonnet-kubeflow

ks env add cloud

VERSION=v0.2.7
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/${VERSION}/kubeflow
ks pkg install kubeflow/core@${VERSION}
ks pkg install kubeflow/tf-serving@${VERSION}
ks pkg install kubeflow/tf-job@${VERSION}
ks pkg install kubeflow/seldon@${VERSION}

# generate the kubeflow-core component from its prototype
ks generate core kubeflow-core --name=kubeflow-core --cloud=gke

# apply component to our cluster
ks apply cloud -c kubeflow-core

cd ..

kubectl get all 

```

**Comment by connected-bsamadi** [comment]
Since I now have a stable Kubeflow 0.3 deployment, I will continue with that. Thank you!
