### ISSUE TITLE
DeepVariant Example

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#3]
[DeepVariant](https://github.com/google/deepvariant) might make an interesting. 

This could be a nice example to illustrate various aspects such as 
 
  - Preprocessing
  - Pipelines.
  - Large scale training

**Comment by cwbeitel** [comment]
Yeah definitely I could see this as a good example for demonstrating a preprocessing workflow feeding into training as well as a good end-to-end demonstration.

**Comment by texasmichelle** [comment]
Anyone still interested in pursuing this?
