### ISSUE TITLE
[code_search] Dataflow job to preprocess the dataset is really slow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#300]
I'm running the Dataflow job to preprocess the data (produce CSV).

Dataflow is indicating only 90 elements/s being processed and indicating days of wall time. This seems awfully slow. 

Based on the graph it seems like the big bottle neck is the tokenize code step.

**Comment by jlewi** [comment]
![dataflow_graph png](https://user-images.githubusercontent.com/777219/47959074-69ed9100-df98-11e8-99de-ad81c806ae4d.png)

**Comment by jlewi** [comment]
Could we be hitting this issue?
https://stackoverflow.com/questions/48463200/debugging-slow-reads-from-bigquery-on-google-cloud-dataflow

One way to debug it might be to export the data to GCS and read from GCS instead of BigQuery.

Or we could read the entire dataset from BigQuery (as opposed to doing a query); and then do the filtering and preprocessing inside Dataflow.

**Comment by jlewi** [comment]
I suspect the problem is this line right here:
https://github.com/kubeflow/examples/blob/acd80077175b619c12989a23c9d7bd2c2095da69/code_search/src/code_search/dataflow/utils.py#L17

We are loading the spacy model on every call to tokenize. Loading the model is really slow; we should only do that once and then reuse it across invocations.

**Comment by jlewi** [comment]
@IronPan I'll submit a PR soon that will improve the performance otherwise the job won't run in a reasonable amount of time.

**Comment by IronPan** [comment]
Thanks great to know!
