### ISSUE TITLE
[code_search] jsonnet overrides don't work as expected

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#308]
The ksonnet is structured such that we define two dictionaries of common parameters "t2t-job"
and "t2t-code-search"
https://github.com/kubeflow/examples/blob/master/code_search/kubeflow/components/params.libsonnet#L4

These parameters can then be used by a variety of different components.

This works as long as we use the default parameters or change the parameter for all environments.

What doesn't seem to work is overriding these parameters on an environment specific basis.

For example, we'd like to be able to override t2t-job["outputDir"] for a specific environment "myenv" and then have all components use that value in environment "myenv"; but that doesn't appear to happen.

**Comment by jlewi** [comment]
I wonder if the correct thing to do here is to take advantage of global parameters.
https://github.com/ksonnet/ksonnet/blob/master/docs/concepts.md

Right now we're defining pseudo modules. Here's the relevant jsonnet code in params.libsonnet for my environment

```
local envParams = params + {
  components+: {
    "t2t-code-search"+: {
      workingDir: 'gs://code-search-demo/20181103',
    },
    "t2t-code-search-datagen"+: {
      workingDir: 'gs://code-search-demo/20181104',
      dataDir: 'gs://code-search-demo/20181104/data',
      project: 'code-search-demo',
      githubTable: '',
    },
    "submit-preprocess-job"+: {
      workingDir: 'gs://code-search-demo/20181104',
      dataDir: 'gs://code-search-demo/20181104/data',
      project: 'code-search-demo',
      githubTable: '',
    },
  },
};

{
  components: {
    [x]: envParams.components[x] + globals
    for x in std.objectFields(envParams.components)
  },
}
```

So if we set a global I think it will automatically be added to every component and I think we can specify globals per environment.

This seems much easier to reason about then what we are currently doing which is relying on late binding.

**Comment by jlewi** [comment]
Downside of using globals is that they can't be easily set via command line (at least not with 0.12).

**Comment by kkasravi** [comment]
> The ksonnet is structured such that we define two dictionaries of common parameters "t2t-job"
> and "t2t-code-search"
> https://github.com/kubeflow/examples/blob/master/code_search/kubeflow/components/params.libsonnet#L4
> 
> These parameters can then be used by a variety of different components.
> 
> This works as long as we use the default parameters or change the parameter for all environments.
> 
> What doesn't seem to work is overriding these parameters on an environment specific basis.
> 
> For example, we'd like to be able to override t2t-job["outputDir"] for a specific environment "myenv" and then have all components use that value in environment "myenv"; but that doesn't appear to happen.

It might be because we define params to be 

    local params = _env + _params,

(see jupyterhub.libsonnet for example) which really should be reversed 

    local params =  _params + _env,

but is that way because we used to supply a namespace override in params.

**Comment by jlewi** [comment]
This issue is specific to the code search example. I don't think we are adding env and params here.

What we're doing in the ksonnet app for this example is defining a virtual component "t2t-code-search"
https://github.com/kubeflow/examples/blob/master/code_search/kubeflow/components/params.libsonnet#L20

Whose parameters are used in other places

https://github.com/kubeflow/examples/blob/master/code_search/kubeflow/components/params.libsonnet#L77

```
    "search-index-server": {
      name: 'search-index-server',
      problem: $.components['t2t-code-search'].problem,
      dataDir: $.components['t2t-code-search'].workingDir + '/data',
      lookupFile: $.components['t2t-code-search'].workingDir + '/code_search_index.csv',
      indexFile: $.components['t2t-code-search'].workingDir + '/code_search_index.nmslib',
      servingUrl: 'http://t2t-code-search.kubeflow:9001/v1/models/t2t-code-search:predict',
    },
```

So if we override workingDir for a specific environment; we'd like that value to be picked up in the search-index-server in the corresponding environment. That doesn't appear to be happening. I think this is an issue with how ksonnet applies the environment specific parameter overrides.

If we use globals it works as expected.

**Comment by kkasravi** [comment]
I think we should look at modules - their use would allow easier groupings. 

I've been experimenting with it for notebooks

```
# Create modules - groupings of components
ks module create ui
ks module create services
ks module create notebooks

# generate components into above modules
ks generate ambassador ambassador --ambassadorServiceType=LoadBalancer --platform=${KUBEFLOW_PLATFORM} --module services
ks generate centraldashboard centraldashboard --module ui
ks generate metacontroller metacontroller --module notebooks
ks generate profiles profiles --module notebooks
ks generate notebooks notebooks --module notebooks

# Generate all required components
ks generate pytorch-operator pytorch-operator
ks generate ambassador ambassador
ks generate jupyterhub jupyterhub
ks generate centraldashboard centraldashboard
ks generate tf-job-operator tf-job-operator
ks generate metacontroller metacontroller
ks generate profiles profiles
ks generate notebooks notebooks

# create a notebooks environment to run notebooks
ks env add notebooks --namespace=$namespace
ks env current --set notebooks
ks env targets default --module notebooks --module services --module ui
ks show notebooks
```

**Comment by jlewi** [comment]
Here's another idea.

* In experiments.libsonnet we define named sets of parameters corresponding to different sets of parameters.

* In a particular environment we set a global parameter indicating the experiment to use; we can then load the appropriate parameters dictionary from experiments.libsonnet.

**Comment by jlewi** [comment]
Lets use this issue to track refactoring the ksonnet per the previous component to avoid using a virtual component to share parameters.
