### ISSUE TITLE
[mnist] use the kubeflow official CI system to build example images

### ISSUE THREAD

**Issue by chenzhiwei** [kubeflow/examples#319]
This is a follow up of PR: https://github.com/kubeflow/examples/pull/316

Detailed can be found inside the PR.

All the example images should be either the opensource project official images or the kubeflow official CI images. See here: https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#image-auto-release

**Comment by texasmichelle** [comment]
Any interest in completing this follow-on?
