### ISSUE TITLE
[code_search] Create a pipeline to generate and update the index of embeddings

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#349]
We'd like to create a pipeline to update the code embeddings with the latest data in GitHub.

The pipeline should consist of three steps

1. Run the Dataflow job to compute embeddings
  
   * ksonnet componet is 
https://github.com/kubeflow/examples/blob/master/code_search/kubeflow/components/submit-code-embeddings-job.jsonnet

   * We should give the output a unique directory

1. Run the K8s job to convert csv files to nmslib index

    * https://github.com/kubeflow/examples/blob/master/code_search/kubeflow/components/search-index-creator.jsonnet

1. Push a commit/or create a PR to update the nmslib index.

    * #348 is updating the ksonnet component to deploy the UI
    * What we want is to run a script that will change the value of the arguments lookupFile and indexFile
  *https://github.com/kubeflow/examples/blob/ab35c85fd91e52b87cc4068fa4bd389a783665a1/code_search/kubeflow/components/search-index-server.jsonnet#L48

**Comment by texasmichelle** [comment]
Has this issue been resolved?
