### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by happyhuman** [kubeflow/examples#362]
There is a broken link in this page:
https://github.com/kubeflow/examples/blob/master/github_issue_summarization/01_setup_a_kubeflow_cluster.md

The link is from "Bringing up a Notebook", pointing to https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#bringing-up-a-jupyter-notebook which does not exist.

**Comment by azmikamis** [comment]
This is already fixed in https://github.com/kubeflow/examples/commit/b69cf36a39d3a4406453b44491f8dcffafdfee61.

Link was updated to https://www.kubeflow.org/docs/guides/components/jupyter/.
