### ISSUE TITLE
[code_search] Configure pipeline to compute code embeddings to run regularly

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#374]
#349 added a pipeline for computing the code embeddings.

We'd like to be able to schedule this pipeline to run regularly.

/assign @IronPan

**Comment by IronPan** [comment]
The scheduled pipeline is a configuration in the UI. The pipeline python definition doesn't need to anything. We can leave this open till we have a periodically pipeline working in the demo cluster.

**Comment by jlewi** [comment]
@IronPan Is there no way to programmatically (ideally declaratively) define a scheduled run? Is there an existing feature request for this?

**Comment by IronPan** [comment]
The scheduled workflow CRD is the underlying controller. So there are multiple ways of define the scheduled pipeline
- through UI 
- through Pipeline API (restful API)
- through scheduledworkflow CRD API (declarative)

I hope that we can use UI to demo. It would really help promoting the pipeline team's work.

**Comment by IronPan** [comment]
I see. Pipeline system doesn't support declaritive for now. Please feel free to open an issue to pipeline project if you think this is critical.
