### ISSUE TITLE
[GH Issue Summarization] Deploy GH web app on kubeflow.org and make it widely accessible

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#39]
I think it would be interesting to deploy the web app and model on a K8s cluster and make it publicly available.

This would be a good test bed for a variety of things; e.g. periodic training and rollouts; monitoring etc...

**Comment by texasmichelle** [comment]
This is complete, right?
http://gh-demo.kubeflow.org/

**Comment by jlewi** [comment]
Yes it has been fixed.
