### ISSUE TITLE
Add ngraph example

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/examples#412]
Add an example of ngraph under kubeflow/examples

- [ ] Provide link to ngraph and overview of [ngraph](https://ai.intel.com/intel-ngraph/) 
- [ ] Provide an e2e example including the dockerfile
- [ ] Include tensorboard in the e2e example with screen shots of ngraph info

**Comment by kkasravi** [comment]
yes, it depends on https://github.com/kubeflow/kubeflow/issues/2058

**Comment by texasmichelle** [comment]
Still interested in pursuing this, Kam?

**Comment by kkasravi** [comment]
You can close this, a different example will be uploaded
