### ISSUE TITLE
[xgboost_ames_housing][help_wanted] How do I copy the training data to the persistent volume?

### ISSUE THREAD

**Issue by azmikamis** [kubeflow/examples#417]
After I create the persistent volume and claim, how do I get the training dataset on it?

I tried to follow the instructions in https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/ but I realised I don't have permissions to write to `/mnt`.

**Comment by azmikamis** [comment]
At first, I created a `dataaccess` pod and configured it to use the created claim. I was able to copy the training dataset to the persistent volume using `kubectl cp train.csv dataaccess:/mnt/xgboost/ames_dataset/`.

However the `xgboost` pod still failed with `IOError: File /mnt/xgboost/ames_dataset/train.csv does not exist`.

I created 2 more volumes and claims so the number of volumes/claims is now equals to the number of nodes in my cluster. Then, I can see the training iterations in the `xgboost` pod logs and `housing.dat` was saved on the last volume i created. After which the pod's status becomes `CrashLoopBackOff` and restarts.

1. Do I need to create as many volumes and claims as the number of nodes in my cluster?
2. If I have more than 1 node in my cluster, how can I know which volume in the cluster the `xgboost` pod will read/write to?
3. Is it usual to let the `xgboost` pod run to end with `CrashLoopBackOff` and let it restart? Won't the `housing.dat` saved be different every time?

**Comment by azmikamis** [comment]
After playing around more with Kubernetes, I understand the problems faced in this example now.

1 & 2. If the cluster is created by `kfctl.sh`, we can just create a `pvc` on the available storage which is on GCE persistent disk rather than using `hostPath`. Then we can create pods to attach to the `pvc` and download the training data, from the given public GCS bucket for example.
3. The `xgboost` pod should rather be a job that will have status `Completed` once training ends. However, that would prevent from being able to "download" `housing.dat` through the pod.

Maybe it will make more sense to just make `housing.py` read the training set and write the model on GCS.

**Comment by texasmichelle** [comment]
@puneith what do you think of this suggestion?

**Comment by puneith** [comment]
@azmikamis to answer your original question you make changes in the Dockerfile and download data from whereever e.g., GCS

https://github.com/kubeflow/examples/blob/master/xgboost_ames_housing/Dockerfile

And now looking at the Dockerfile I realize that should be part of this example anyways.
