### ISSUE TITLE
[Github Summarisation] Add support to store the training data into Minio

### ISSUE THREAD

**Issue by hackintoshrao** [kubeflow/examples#435]
Object storage systems are becoming dominant as storage backend for analytical and ML workloads. Minio being an open source alternative for S3 and its cloud nativeness makes it an attractive fit to the Kubeflow's ecosystem. Would like to start adding more examples where the data to be trained is stored in Minio and the Tensorflow model directly reads from it. To begin with the Github summarisation examples looks promising. Would like it to take this up.

**Comment by texasmichelle** [comment]
I think that would be great if you're still up for it!

**Comment by hackintoshrao** [comment]
@texasmichelle : Can I still take this up?
