### ISSUE TITLE
Version 0.4 - TensorFlow Version Supported

### ISSUE THREAD

**Issue by jonf78** [kubeflow/examples#441]
Hi,

I watched a video from KubeCon last night and it was mentioned that version 0.4 will be released soon. I have a quick query on what will be the latest version of TensorFlow that will be supported/work at this version. Apologies if the query doesn't actually make sense as this is my first step into KubeFlow / ML on Kubernetes :) 

Thanks
jon

**Comment by texasmichelle** [comment]
This is a great question for Slack or the mailing list, since you'll get more timely responses :)

Signup details [here](https://www.kubeflow.org/docs/about/community/) if you're not already a member. Welcome!
