### ISSUE TITLE
Redundant multi-stage Dockerfile 

### ISSUE THREAD

**Issue by hholst80** [kubeflow/examples#442]
xgboost_ames_housing Dockerfile uses a FROM statement that is not needed and only causes overhead.

https://stackoverflow.com/questions/53546176/empty-multi-stage-build-in-a-dockerfile/53549404#53549404

**Comment by hholst80** [comment]
Created PR https://github.com/hholst80/examples/pull/1

**Comment by texasmichelle** [comment]
Thanks for the fix! If you submit as a PR to this repo (rather than your own fork), I'm happy to review.
