### ISSUE TITLE
[codelab-e2e-gis-feedback]:

### ISSUE THREAD

**Issue by amalts** [kubeflow/examples#443]
Below command from **Kubeflow End to End: GitHub Issue Summarization** in **"Install Kubeflow with Seldon"** page (Page 3) fails with 404 error.

**Section :** 
Install packages and generate core components

**Command :**
`ks pkg install kubeflow/tf-job@${KUBEFLOW_VERSION}`

**Error:**
`ERROR resolving package metadata: kubeflow/tf-job@v0.3.4: GET https://api.github.com/repos/kubeflow/kubeflow/contents/kubeflow/tf-job/parts.yaml?ref=5823eca40f29687e24447f4717f5f21437ad75be: 404 Not Found [] `

**Comment by jlewi** [comment]
@amalts are you referring to 
https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis/index.html#0
?

I think the instructions are outdated.
In 0.3 we refactored the packages and the tf-job package is no longer there.
https://github.com/kubeflow/kubeflow/tree/v0.3-branch/kubeflow

The error above indicates its trying to install 0.3.4 but the [codelab](https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis/index.html#0)

is still using 0.2.

@texasmichelle how do we go about updating the codelab?

**Comment by texasmichelle** [comment]
For now the codelab only works with v0.2.0-rc.1. I actually just pushed changes to the Qwiklabs repo to update this to v0.4.0-rc.2 and use `kfctl`, but there's still a bit more work to be done, including finding a good way to keep it in sync with the [CLAAT version](https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis). Stay tuned!

**Comment by texasmichelle** [comment]
This lab has been updated to v0.5, so this should be resolved.
