### ISSUE TITLE
[GH Issue] directory distributed missing for github_issue_summarization

### ISSUE THREAD

**Issue by benjaminhuo** [kubeflow/examples#461]
Directory distributed is missing for github_issue_summarization.

Nowhere to find stuff for below cmd:
kubectl create -f distributed/storage.yaml
kubectl create -f distributed/tfjob.yaml

Below links are broken:
https://github.com/kubeflow/examples/tree/master/github_issue_summarization/distributed

**Comment by Luke035** [comment]
Just to be sure: is this meaning that for github-issue-summarization example there's no more valid code in the repo for distributed training? From #196 it seems that with #265 it should work again. 
I'd like to learn more on how to use estimator and distributed training (I'm getting started on KUBEFLOW), any suggestion on where to find other examples in the repo that address this?
