### ISSUE TITLE
[mnist_pytorch] Remove specific modules from .pylintrc ignore-patterns

### ISSUE THREAD

**Issue by dsdinter** [kubeflow/examples#464]
Remove py,mnist_DDP.py and mnistddpserving.py modules from .pylintrc ignore-patterns , adding specific exceptions using inline comments instead.

We should still keep the autogenerated Python GRPC modules:
object_detection_grpc_client.py
prediction_pb2.py
prediction_pb2_grpc.py

**Comment by texasmichelle** [comment]
Is this issue still outstanding?

**Comment by dsdinter** [comment]
It is still outstanding. Will try to implement next week.
Thanks for the heads up!
