### ISSUE TITLE
Create tf-serving examples for models trained using higher level APIs

### ISSUE THREAD

**Issue by bkungfoo** [kubeflow/examples#48]
Example: Estimator and Keras API training to serving + Unit testing
Priority: P1 - It's not a must have, but could be a great contribution to the TF community, where many data scientists train using one of these two APIs.

The k8s-model-server component in Kubeflow currently contains an inception client example that interacts with a custom model graph: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_saved_model.py

ML practitioners often use TF estimator and Keras APIs to train models, as it greatly simplifies the training and validation process. However, converting these to servable models can be trickier and harder to debug. Add some examples of how to build servable models trained using Estimator and Keras APIs, and unit test examples.

**Comment by jlewi** [comment]
@yupbank Presented some demos of exporting a scikits learn model for serving with TF Serving.
https://github.com/yupbank/demo_kubeflow

https://github.com/yupbank/tree_to_tensorflow

https://github.com/yupbank/tree_to_tensorflow/tree/add-spark

**Comment by yupbank** [comment]
^ yeah, that use tensorflow estimator.

**Comment by bkungfoo** [comment]
Thanks @jlewi and @yupbank . In general, do you think TF training-to-serving code belongs in Kubeflow examples?

As an example, I refactored the Estimator and Keras ResNet examples from my notebooks,
 e.g. https://github.com/google-aai/tf-serving-k8s-tutorial/blob/master/estimator_training_to_serving_solution.ipynb into a forked branch below. The example is more involved with the Estimator API since it customizes the client RPC call by changing the default model_fn. 

For the Estimator, training uses an input tf-record with many fields, and returns the top class and probability during prediction. Keras ResNet50 model accepts raw image tensors as input and returns all 1001 classes and probabilities. The example below shows how to change both graphs so the model server accepts encoded images as input, and returns top k results. Also added example unit tests.

https://github.com/bkungfoo/examples/tree/training-to-serving-examples/training_to_serving

**Comment by yupbank** [comment]
>  do you think TF training-to-serving code belongs in Kubeflow examples?

That's really a good question, I think we should advocate this kind of example, this piece of knowledge is critical for proper usage of tensorflow/serving and kubeflow. The tensorflow community should do a better job at this, mean while we can add some example under kubeflow.

Even the tensorflow/serving people get confused over the correct usage https://github.com/tensorflow/serving/issues/794

**Comment by bhack** [comment]
Partially related to https://github.com/kubeflow/tf-operator/issues/61

**Comment by bhack** [comment]
See also https://github.com/tensorflow/tensorflow/issues/17890 and https://github.com/tensorflow/tensorflow/issues/16182

**Comment by bhack** [comment]
@ewilderj

**Comment by jlewi** [comment]
So can we do this in the context of our existing E2E solutions?

For example

- #42 is creating an example using the tf.Estimator API
- The GitHub issue summarization example is using Keras.

**Comment by bhack** [comment]
@jlewi is the summarization using `tf.model_to_estimator`?

**Comment by jlewi** [comment]
@bhack I don't know.

**Comment by bhack** [comment]
@jlewi no it is using `tf.layers` for model definition not `tf.keras`

**Comment by texasmichelle** [comment]
Anyone still interested in pursuing this?
