### ISSUE TITLE
Error while loading shared libraries: libcuda.so.1

### ISSUE THREAD

**Issue by tech98321469320842** [kubeflow/examples#483]
Hi,

I am try to start the following example from this repo:

--> https://github.com/kubeflow/examples/tree/master/object_detection

Every step of the tutorial works great, but unfortunately the pod always crashes directly after startup because of this missing lib located in CUDA:

```
kubectl --namespace=kubeflow logs deployment/coco-v1 -c coco
/usr/bin/tensorflow_model_server: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
```

I think it is connected with the fact that I don't have a GPU connected to the kubernetes cluster.
I tried to set:
`ks param set model1 numGpus 0`

But that also does not help.

So my question is:
Is there any way to get this example up and running without a mounted GPU?

Thanks a lot! :)

**Comment by jlewi** [comment]
If you modify the example to use the CPU version of tensorflow then it should work fine without a GPU.

**Comment by texasmichelle** [comment]
@tech98321469320842 were you able to use this workaround to resolve your issue?
