### ISSUE TITLE
mnist_predict test is failing with 503

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#494]
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples
Last successful run was 01/24
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/kubeflow-periodic-examples/4

Failed run:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/kubeflow-periodic-examples/18

```
 RuntimeError: Request to https://35.229.30.77/api/v1/namespaces/mnist-18/services/mnist-test-18:8500/proxy/v1/models/mnist:predict exited with status code: 503 and content: b"Error: 'ssh: rejected: connect failed (Connection refused)'\nTrying to reach: 'http://10.40.0.36:8500/v1/models/mnist:predict'"
```
Its weird that its failing with with a 10.40.0.36 address.

I think the way to debug this would be 

1. Spin up a Kubeflow cluster
1. Deploy mnist on that cluster
1. Run the mnist test manually against that cluster and see if you can repo.

**Comment by jinchihe** [comment]
@jlewi Seems I also hit the problem during auto testing for the PR #492.

**Comment by jinchihe** [comment]
@jlewi I `/retest` the tests in the PR #492 , seems the phenomenon of the problem seems to have changed. I try to deploy mnist on the on-prem kubeflow cluster, did not get the root course so far. Thanks.

**Comment by eLco** [comment]
> @jinchihe any interest in trying to reproduce it and debug it as mentioned above?
> 
> Alternatively is there a way to use pytest to mark it as an expected failure?

@jlewi you can mark test as expected failure using this annotation
```
@pytest.mark.xfail
def test_function():
```
Quote from docs:
```
This test will be run but no traceback will be reported when it fails. Instead terminal reporting will list it in the “expected to fail” (XFAIL) or “unexpectedly passing” (XPASS) sections.
```

**Comment by jlewi** [comment]
Judging from the periodic runs it looks like there are periods where it passes and periods where it doesn't
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples
