### ISSUE TITLE
Unable to open the webpage at https://kubeflow.example.com/hub

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/examples#500]
Hello all, I'm now trying the Code Search example in kubeflow examples (https://github.com/kubeflow/examples/tree/master/code_search). I'm not able to access Kubeflow Hub https://kubeflow.example.com/hub and it looks like the site keeps on loading until it times out.

**Comment by CraigSterrett** [comment]
The link is just an example and it is probably a bit misleading that it appears as a hyperlink.  You first have to spin up your own kubeflow cluster and have your Jupyter hub available at https://kubeflow.example.com for that link to work.
The second sentence under "Getting Started"
NOTE: We will assume that the Kubeflow cluster is available at kubeflow.example.com. Make sure you replace this with the true FQDN of your Kubeflow cluster in any subsequent instructions.

**Comment by krishnadurai** [comment]
@CraigSterrett thanks for pointing this out. I'll try these steps.
