### ISSUE TITLE
[codelab-e2e-gis-feedback]:

### ISSUE THREAD

**Issue by alvisememo** [kubeflow/examples#503]
Friction log:
- kubectl is never installed, it should be considered as a step before creating a cluster.
- instead of using $HOME as the directory to which store, unzip and manage files, there should be a top level directory variable like "EXPERIMENT_DIR=your_exp_dir" in which everything is included.

WDYT?

**Comment by texasmichelle** [comment]
kubectl is included with Cloud Shell, so in this case it would be redundant to add installation instructions. Good idea about adding an experiment dir. Are you interested in adding that modification to the lab? If so,  ping me on kubeflow slack & I'll point you at some resources: `@michelle`. It's as straightforward as editing a Google doc.
