### ISSUE TITLE
Google Cloud Shell dies even on Booster Mode

### ISSUE THREAD

**Issue by ashishML** [kubeflow/examples#504]
Following the tutorial on https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html#1 the Google Cloud Shell keeps dying repeatedly when trying to deploy the training job to the cluster using the command:-

ks apply default -c train

The instructions mention to enable Boost Mode but it keeps dying repeatedly.

**Comment by jlewi** [comment]
@ashishML Have you tried running from a command line or from a VM?

@Dansanche @amygdala @texasmichelle Have you observed this problem?

**Comment by amygdala** [comment]
No, but I've not tried that specifically. (The contexts in which I've used the cloud shell with KF have been only in conjunction with using the web launcher for deployment + Pipelines for launching training.) 

It seems unintuitive though, that a 'ks apply' would be compute or memory intensive enough to crash the shell. Dan, I think you may have been the last one to test this codelab?-- did you ever see this?

**Comment by DanSanche** [comment]
That's strange, I've never seen this error on boost mode. Is it possible you have another process running in the background that may be eating up your resources? I'd recommend trying to restart the cloud shell session (there's an option in the same menu as the boost mode button) to see if that helps

**Comment by texasmichelle** [comment]
The reason Boost Mode instructions were added is to accommodate docker image builds. The `ks apply` failure is likely caused by something else. In any case, the lab was recently updated and ksonnet was replaced by kustomize, so I believe this issue has been resolved.
