### ISSUE TITLE
FAILS: docker build mnist/web-ui -t $UI_PATH; no space left on disk

### ISSUE THREAD

**Issue by opus111** [kubeflow/examples#514]
Following the steps "Deploying the UI"/"Building the Container"
https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html?index=..%2F..io2018#4

Apparently fails because "No space left on device"

$ docker build mnist/web-ui -t $UI_PATH
Sending build context to Docker daemon  11.84MB
Step 1/14 : FROM ubuntu:16.04
 ---> 7e87e2b3bf7a
Step 2/14 : MAINTAINER "Daniel Sanche"
 ---> Using cache
 ---> 9c71213be2c2
Step 3/14 : RUN apt-get update && apt-get install -y --no-install-recommends         build-essential         curl         libfreetype6-dev         libpng12-dev         libzmq3-dev         pkg-config         python3         python-dev         rsync         software-properties-common         unzip         &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 98c99e562018
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Ign:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
.
.
.
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Reading package lists...
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.91.26 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.162 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends         build-essential         curl         libfreetype6-dev         libpng12-dev         libzmq3-dev         pkg-config         python3         python-dev         rsync         software-properties-common         unzip         &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by jlewi** [comment]
It looks like you ran out of disk space.

**Comment by opus111** [comment]
Agreed, but there is plenty of space on my laptop.  Is it building on some virtual disk?

**Comment by opus111** [comment]
Fixed it.  It was something to do with my local Docker environment

https://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device

Apparently I had 'dangling' volumes

docker volume rm $(docker volume ls -qf dangling=true)
