### ISSUE TITLE
[codelab-e2e-gis-feedback]: Bug in SERVING_IMAGE environment variable

### ISSUE THREAD

**Issue by mbittmann** [kubeflow/examples#517]
In this training lab: 
https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis/index.html#2

There is a line `export SERVING_IMAGE=gcr.io/kubeflow-examples/issue-summarization-model:v20180718-g98ed4b4-codelab`

This image does not currently exist in the container registry. There is an image: `gcr.io/kubeflow-examples/issue-summarization-model:v20180718-g98ed4b4-qwiklab`

Note the existing one ends with `qwiklab` whereas the one in the training ends in `codelab`

**Comment by texasmichelle** [comment]
Added a tag `v20180718-g98ed4b4-codelab` to the serving image. Thanks for filing this issue!
