### ISSUE TITLE
bug in "Introduction to Kubeflow on Google Kubernetes Engine"

### ISSUE THREAD

**Issue by bandurin-strike** [kubeflow/examples#523]
Hello,

I am going along the tutorial at
https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html#2
I am using Google Cloud Shell.
Everything worked fine until i reached this place:

"Now that all the parameters are set, we can deploy the training job to the cluster:"
> ks apply default -c train

Below i attached a screenshot with the error message:

<img width="1197" alt="screen shot 2019-03-04 at 3 17 55 pm" src="https://user-images.githubusercontent.com/21246043/53763571-bbe3ec00-3e90-11e9-8896-dbf1159d8170.png">

Please advise what i am doing wrong.
You can reply me directly to my email bandurin@gmail.com.

Thanks,
Dmitry

**Comment by jlewi** [comment]
@sarahmaddox @DanSanche Did you run into this problem?

**Comment by sarahmaddox** [comment]
I didn't run into the problem, but I didn't use Cloud Shell.

**Comment by DanSanche** [comment]
Hmm that's a new one. No, I don't know what would cause that. @bandurin-strike were you in boost mode?

**Comment by romankazinnik** [comment]
Another problem with 'ks apply':

**Comment by DanSanche** [comment]
How did you create your cluster @romankazinnik ? That's a different issue, it looks like your cluster doesn't know about Kubeflow's TFJob resource

**Comment by romankazinnik** [comment]
I am using an existing pre-set dedicated for Kubeflow clustter. What I
should do differently to make the lab to work in my case?

**Comment by DanSanche** [comment]
It's likely there is a version mismatch between the version on your cluster and the one used in the lab. If you want to discuss this in more detail, you should open a new issue (and upload some more details) so we don't go too far off on a tangent here

**Comment by abdennour** [comment]
Same issue here in this [lab](https://www.qwiklabs.com/focuses/5169?parent=catalog)

```
ks apply default -c tfjob
ERROR handle object: patching object from cluster: merging object with existing state: unable to recognize "/tmp/ksonnet-mergepatch851727764": no matches for kind "TFJob" in version "kubeflow.org/v1beta1"


```

**Comment by abdennour** [comment]
In cloud shell, make sure you've already enabled "Boost Mode"

![image](https://user-images.githubusercontent.com/1788384/59920430-27979800-9433-11e9-8a06-e38886b8df05.png)

**Comment by texasmichelle** [comment]
It could be a version mismatch with ksonnet. Could you paste the output of `ks version`?

**Comment by texasmichelle** [comment]
The intro codelab in the description of this bug has been updated to replace ksonnet with kustomize, so @bandurin-strike's issue should be resolved.

As for the E2E Qwiklab reported by @abdennour, there is a new version staged to be published which has not yet moved to kustomize. Are you going through the lab using Qwiklabs GCP credentials or are you issuing the commands on an existing cluster like @romankazinnik? If you're using qwiklabs resources, the new version will potentially resolve the issue.
