### ISSUE TITLE
tfjob_test.py for GIS needs to be updated due to TFJob operator python refactoring

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#526]
See test failure:
https://github.com/kubeflow/examples/pull/522#issuecomment-472628220

The test
https://github.com/kubeflow/examples/blob/8a26b23e3d35d5993d93e8b9ecae52371598d1cc/github_issue_summarization/testing/tfjob_test.py#L31

Is still doing 

```
from py import tf_job_client #pylint: disable=no-name-in-module
```

We probably need to update the E2E test to set the python path correctly and then import it as 

```
from kubeflow.tf_operator import tf_job_client
```
https://github.com/kubeflow/tf-operator/tree/master/py/kubeflow/tf_operator

/assign @zabbasi

**Comment by zabbasi** [comment]
#527
