### ISSUE TITLE
codelabs tutorial should set namespace to kubeflow for ksonnet environment

### ISSUE THREAD

**Issue by a097253** [kubeflow/examples#529]
If you follow the [codelabs instructions](https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html#2) (unless I missed it), the pod/container for training the MNIST model gets deployed to the `default` namespace.  As a result, the Pod is unable to mount the secret volume `user-gcp-sa`.  

If I set the namespace for the default environment to `kubeflow`, everything works:

```
$ ks env set default --namespace=kubeflow
```
I think the instructions need to make it clear that you should the namespace should be set to `kubeflow` before running:

```
$ ks apply default -c train
```

**Comment by texasmichelle** [comment]
The lab has been updated to replace ksonnet with kustomize, so I believe this issue has been resolved.
