### ISSUE TITLE
No eval result found after distributed training

### ISSUE THREAD

**Issue by NKUCodingCat** [kubeflow/examples#533]
Hey guys, I run mnist/model.py locally and get evaluate result in logs, but I cannot find such in distribution training logs.....do I make something wrong?

**Comment by NKUCodingCat** [comment]
Docker file & python scripts are here:
[No_eval_result.zip](https://github.com/kubeflow/examples/files/3001798/No_eval_result.zip)

I can get evaluation result when I run model.py directly 
```
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2019-03-25-02:44:30
INFO:tensorflow:Saving dict for global step 1000: Acc = 0.953125, global_step = 1000, loss = 0.14597973
```
but such lines are missing in the logs of kubeflow jobs

**Comment by texasmichelle** [comment]
Which instructions are you using to run this example? Please provide a few more specifics about the command you are running. There are very detailed and up-to-date instructions in [this lab](https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html?index=..%2F..index#0) if you have access to a GCP account.

**Comment by NKUCodingCat** [comment]
alright....I found that I should use tensorboard to check data on Shared directory but not just look at logs...(maybe there will be eval in evaluator but I cannot find anything in chief log)
