### ISSUE TITLE
Remove ksonnet from mnist example

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#539]
Since ksonnet is deprecated we should remove ksonnet from the mnist example.

One possible approach would be to use a tool like make, jsonnet, kustomize, or a custom python script to easily generate a set of YAML files customized for a particular user.

**Comment by jinchihe** [comment]
@jlewi  I think the kustomize is good way, but maybe depend on other components. I can try to work on this. Thanks.

**Comment by jlewi** [comment]
@jinchihe Still planning on picking this up? Any timeline? We are aiming to do a demo of Kubeflow with kustomize on 04/30 (#3020) it would be great if part of that demo we could run mnist.

**Comment by jinchihe** [comment]
@jlewi OK, I'm doing this now, local mode has been changed by using kustomize, planed to finish that before the end of this weekend (Apr 27). Not sure the automation tests can be passed, since the tests also need to be modified to drop ksonnet, but will try that later. Thanks.

**Comment by jinchihe** [comment]
/assign @jinchihe 

Status: The example mnist has been updated by replacing ksonnet with kustomize, for training, monitoring and serving. The unit tests are almost done, the Readme file also been changed. The new files and code have been uploaded to [my repo](https://github.com/jinchihe/Working/tree/master/kubeflow/examples/mnist) temporary. 

Seem the effort is bigger than estimated :-), I'm going to update the auto test related,  then will create a PR for this once finished. Thanks.
