### ISSUE TITLE
Sketch out recommendation example

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#54]
I think it would be very valuable to have a recommendation example. The purpose of this issue is to identify a scenario and dataset around which we could build a solution.

Some possible datasets

GitHub Data

  -  We could recommend repositories based on stars
  -  Issues/PRs (comments could be used to indicate a user was interested in an issue)
  - Recommend reviewers for PRs

Hacker News or Reddit
  - I think both datasets are available publicly in BigQuery
  
The [MovieLens](https://grouplens.org/datasets/movielens/) data seems less interesting because it isn't updated frequently.

**Comment by hamelsmu** [comment]
cc: @wingr @omoju

**Comment by hamelsmu** [comment]
We could do something where we take the hidden state(s) produced by the encoder in the seq2seq model and use those to do nearest neighbor lookup for recommendations for new Github issues.  This would be really cool example of multiple things you can do with the same model you already built and generally shows off the versatility of deep learning (that you get a reuseable feature extractor every-time you build a model).

**Comment by hamelsmu** [comment]
Also I have an example almost ready for that (just need to polish it a little), incase you would find that interesting.

**Comment by jlewi** [comment]
Absolutely.

At Kubecon I will be talking about the existing GH issue (I'll send you my slides so you can take a look). I know David is really excited about recommendations because there's a lot of interest in that.

One of the things we want to highlight at Kubecon is being able to scale out e.g distributed since that's one of the benefits of TFJob.

@ankushagarwal is working on that kubeflow/examples#43 

Recommendations + Distributed training would be amazing.

/cc @aronchick

**Comment by texasmichelle** [comment]
Anyone still interested in pursuing this?
