### ISSUE TITLE
Demo github-issue-summarization - data and images not available anymore - Request violates VPC Service Controls.

### ISSUE THREAD

**Issue by rbo** [kubeflow/examples#545]
Hi everyone,

some necessary parts for the github-issue-summarization demo are not available anymore:

**https://storage.googleapis.com/kubeflow-examples/github-issue-summarization-data/github-issues.zip**
```
<Error>
<Code>SecurityPolicyViolated</Code>
<Message>Request violates VPC Service Controls.</Message>
<Details>Request is prohibited by organization's policy</Details>
</Error>
```

Mention at 
- https://github.com/kubeflow/examples/blob/master/github_issue_summarization/ks_app/components/data-downloader.jsonnet#L26
- https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/Training.ipynb#L61

**gcr.io/kubeflow-dev/issue-summarization-notebook-cpu:latest**
 ```
Your access is denied by VPC Service Controls. Please contact your organization's administrator for more information.
Tracking Number: 5908589009411772394
```
Mention at
 - https://github.com/kubeflow/examples/blob/master/github_issue_summarization/01_setup_a_kubeflow_cluster.md#kubeflow-setup

The Container Image is not the problem, I build my own with a new tensorflow version: [quay.io/kubeflow-examples/issue-summarization-notebook-cpu:openshift](https://quay.io/repository/kubeflow-examples/issue-summarization-notebook-cpu) | [Dockerfile](https://github.com/rbo/kubeflow-examples/blob/openshift/github_issue_summarization/notebooks/Dockerfile)

Is there any way to get or build the github-issues-data?

Thanks
Robert

**Comment by rbo** [comment]
Found the original zip file: https://www.kaggle.com/davidshinn/github-issues - sadly you have to register to get access

**Comment by thlevy** [comment]
I have the same issue here..
I will be creating a new issue to avoid it to be misclassified by this dummy label-bot ;-)
Thanks
Thom

**Comment by texasmichelle** [comment]
It looks like there is a policy within your organization that is blocking asset downloads. Do you have information from your administrator on what is and isn't allowed? That would help us identify an alternative place to host these files.

**Comment by rbo** [comment]
Good point, I don't know. Today it works:
```
curl -I https://storage.googleapis.com/kubeflow-examples/github-issue-summarization-data/github-issues.zip


HTTP/2 200
```

Nothing changed on my site.

Thanks
Robert

**Comment by texasmichelle** [comment]
Great! Feel free to reopen if you run into issues in the future.
