### ISSUE TITLE
Jupyter image for "GitHub issue summarization" blocked

### ISSUE THREAD

**Issue by thlevy** [kubeflow/examples#547]
Hello,

The "GitHub issue summarization" example can't be launched because the Jupyter image can't be retrieved.
Kubernetes log:
``
Failed to pull image "gcr.io/kubeflow-dev/issue-summarization-notebook-cpu:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/kubeflow-dev/issue-summarization-notebook-cpu/manifests/latest: denied: Request is prohibited by organization's policy
``

Can anyome move this image to a safer place?
Thanks,
Thom

Note: Issue also raised at: https://github.com/kubeflow/examples/issues/545

**Comment by texasmichelle** [comment]
Same question as #545: @thlevy - are you aware of what your organization policy is? What does your administrator consider safe?

**Comment by thlevy** [comment]
I don't  think that I was coming from my organization policy since I tested from my prof company and from my personal ISP.
But, today, the url is now reachable.
Thanks
