### ISSUE TITLE
ks_app doesn't exist, link to components 404s in minst example

### ISSUE THREAD

**Issue by chris-andrasick** [kubeflow/examples#551]

**Comment by jinchihe** [comment]
@chris-andrasick Could you please describe more details for the issue? where you get the error? the `ks` has been replaced by `kustomize` in mnist example, and the `ks_app` has been removed.

**Comment by chris-andrasick** [comment]
The broken link is on the page: https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html#1 (Getting Started section of the Introduction to Kubeflow Tutorial.  Search for "pre-written" to find the exact link.  It points to: https://github.com/kubeflow/examples/tree/master/mnist/ks_app/components which returns a 404.  Hope it helps!

**Comment by jinchihe** [comment]
If so, I think the document is out-of-date in `developers.google` (may be author should update that or draft new one?).  The `ksonnet` is deprecated, we updated accordingly in `kubeflow`. Thanks.

**Comment by texasmichelle** [comment]
This lab has been updated to use kustomize instead of ksonnet, so I believe this is fixed.
