### ISSUE TITLE
examples/mnist/ks_app/components/*': No such file or directory

### ISSUE THREAD

**Issue by kjaugustin** [kubeflow/examples#553]
Introduction to Kubeflow on Google Kubernetes Engine at Codelab needs to be updated with steps to use kustomize instead of ksonnet. The following step throws error.
cp $WORKING_DIR/ks_app/components/* $WORKING_DIR/$KS_NAME/components

No such file or directory

**Comment by jinchihe** [comment]
@kjaugustin for the example mnist, the kssonnet already was repalced by kustomize. thanks.

**Comment by texasmichelle** [comment]
This lab has been updated to use kustomize instead of ksonnet, so I believe this is fixed.
