### ISSUE TITLE
Writing model directly to GCS instead of saving locally and then copying to GCS

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/examples#58]
The tfjob example for github issue summarization saves the model locally and then uploads it to GCS. We should try to write the model directly to GCS.

**Comment by cwbeitel** [comment]
One approach would be to write to a mounted gcePersistentDisk making the example code storage solution agnostic (just writes to some path) and have a separate solution and docs for people to swap around their storage providers.

**Comment by texasmichelle** [comment]
The code has changed so much since this issue was created, do we still care about this? @jlewi was the original requestor in #55

**Comment by texasmichelle** [comment]
[This](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/train.py) is what the code looks like now.
