### ISSUE TITLE
TFJob Quick Start example not working

### ISSUE THREAD

**Issue by crsawyer314** [kubeflow/examples#580]
Trying to run the code exactly as presented in the 'Running the TfCnn example' section of the quick start guide gets me the error "ERROR handle object: patching object from cluster: merging object with existing state: unable to recognize "/tmp/ksonnet-mergepatch436733100": no matches for kind "TFJob" in version "kubeflow.org/v1alpha2"".

The only difference is that I ran `ks generate tf-job-simple ${CNN_JOB_NAME} --name=${CNN_JOB_NAME}` instead of `ks generate tf-job-simple-v1 ${CNN_JOB_NAME} --name=${CNN_JOB_NAME}` because the `-v1` version gave me the error "ERROR no prototype names matched 'tf-job-simple-v1'; a list of partial matches: io.ksonnet.pkg.tf-job-simple-v1beta1"

Any help would be greatly appreciated. Trying to run this on minikube.

**Comment by jinchihe** [comment]
@crsawyer314 Checked which version used in your cluster bu running `kubectl describe crd tfjobs.kubeflow.org`. I think the `kubeflow.org/v1alpha2` is out of date.
