### ISSUE TITLE
[codelab-intro-mnist-feedback]:

### ISSUE THREAD

**Issue by mitsuan** [kubeflow/examples#583]
kustomize build isn't working for 2.1.0

Getting error:
Error: var '{batchSize ~G_~V_ConfigMap {data.batchSize}}' cannot be mapped to a field in the set of known resources

**Comment by jinchihe** [comment]
@mitsuan See details in https://github.com/kubeflow/examples/issues/578, the new version kustomize may changed something, I am going to enhance that to fit new kustomize version. but you can use v2.0.3 to work around.
