### ISSUE TITLE
Clarification needed about EXPORT_DIR in MNIST example

### ISSUE THREAD

**Issue by aginpatrick** [kubeflow/examples#587]
I tried the MNIST example and successfully followed all the steps until the serving of the trained model. Under this section of the doc named "Serve the trained model", they say at point 3 ("Set your model path") to do : `kustomize edit add configmap mnist-map-serving   --from-literal=modelBasePath=${EXPORT_DIR}`

Problem is nowhere in the doc they talk about EXPORT_DIR. So I put what I think should be there (the path of the exported model in my gs bucket, something like: gs://kubeproj-245614-depname-bucket/export/1262282319). When I deploy it with `kustomize build . |kubectl apply -f -` and after that check the deployment by `kubectl describe deployments mnist-gcs-dist`I get the error 

`Error from server (NotFound): deployments.extensions "mnist-gcs-dist" not found``

Would it be related to the EXPORT_DIR guess that I made?

**Comment by aginpatrick** [comment]
I forgot to mention that deployment seems to be created in the workloads (as I see it in the GCP). mnist-gcs-dist is also present in the Services & Ingress list.

**Comment by jinchihe** [comment]
@aginpatrick Which document you are following? I'm pretty sure there is definations in section `Serving the model` of the [README](https://github.com/kubeflow/examples/tree/master/mnist)

```
EXPORT_DIR=gs://${BUCKET}/${MODEL_PATH}/export
```

**Comment by aginpatrick** [comment]
I was following the section "End-to-end Kubeflow on GCP"
(https://www.kubeflow.org/docs/gke/gcp-e2e/) in the offical Kubeflow docs. They forgot to mention the value of EXPORT_DIR. Thank you for clarifying. Unfortunately I already tried to set the EXPORT_DIR to this value and the result is the same: kubectl describe command gives "mnist-gcs-dist" not found even if "mnist-gcs-dist" is found in the list of workloads on the GCP.

**Comment by jinchihe** [comment]
Oh.. Could you please try that following the README file? If that works, could please send to PR to update website?

**Comment by aginpatrick** [comment]
Sure.

**Comment by jinchihe** [comment]
@aginpatrick Any updates for this? Thanks.
