### ISSUE TITLE
Grant access to test clusters to example maintainers

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#588]
E2E tests for examples (like mnist). run against test clusters e.g.

kf-vmaster-nXX
in project kubeflow-ci-deployment.

It can be frustrating and/or impossible to debug failures without access to the clusters.

We should define appropriate groups and access so that maintainers of examples can access
their clusters.

We should define a new Google group here
https://github.com/kubeflow/internal-acls

For people who own the examples; e.g. @texasmichelle, @jinchihe 

We should then figure out what IAM policies to grant them and update the IAM policies defined here
https://github.com/kubeflow/internal-acls/blob/master/gcp_iam_policies/kubeflow-ci.iam.policy.yaml

IAM roles are listed here:
https://cloud.google.com/kubernetes-engine/docs/how-to/iam#kubernetes-engine-roles

I think we should start with 
roles/container.developer

And see if that's sufficient.

Setting the IAM role means they would have access to all GKE clusters in kubeflow-ci-deployment.

That includes all the K8s clusters spun up by our E2E tests.

I think that should be ok.

**Comment by jlewi** [comment]
@jinchihe You should have access to the clusters in project kubeflow-ci-deployment

Could you please confirm by running

```
gcloud --project=kubeflow-ci-deployment container clusters list
gcloud --project=kubeflow-ci-deployment container clusters get-credentials ...
```

And then running 

```
kubectl get crd
```

To ensure you can access the clusters

**Comment by jlewi** [comment]
Before we close out this issue we should document this in kubeflow/examples

**Comment by jinchihe** [comment]
@jlewi Great thanks for this! but sorry... I still have not access to the cluster.
```
hejinchidembp:kfserving hejinchi$ gcloud --project=kubeflow-ci-deployment container clusters list
ERROR: (gcloud.container.clusters.list) ResponseError: code=403, message=Required "container.clusters.list" permission(s) for "projects/kubeflow-ci-deployment". See https://cloud.google.com/kubernetes-engine/docs/troubleshooting#gke_service_account_deleted for more info.
```
I checked the `gcloud info`, seems the mail is `jinchihe@gmail.com`. I tried to changed to `hejinchi@cn.ibm.com` which is added by you, but cannot do that even if I selected the `[2] Log in with a new account` and used `hejinchi@cn.ibm.com` to log in (I added the email as "Alternate mail"). And then check the `gcloud info`, still "jinchihe@gmail.com"...

```
hejinchidembp:kfserving hejinchi$ gcloud info |grep -i account
Account: [jinchihe@gmail.com]
    account: [jinchihe@gmail.com]
```

I wonder could you please also add the "jinchihe@gmail.com" , or any suggestion for this? Thanks again!

**Comment by jlewi** [comment]
@jinchihe Do you have a google account associated with your IBM email? If not could you create one? Its better if we can associate Kubeflow accounts with corporate email addresses and not personal email addresses.

Then run

```
gcloud auth login hejinchi@cn.ibm.com
```

When you run that command it should open a web browser asking you to login. If you don't already have a google account associated with that email you can probably create one.

**Comment by jinchihe** [comment]
@jlewi Yes, I associated with my IBM email with my google account.
When I try to run the `gcloud auth login hejinchi@cn.ibm.com`, open a web browser, and by default that's gmail and I selected the `Use another account` to input IBM email and password, and then still show `Google Cloud SDK wants to access your Google Account jinchihe@gmail.com`, I click `Allow` but screen shows
```
ERROR: (gcloud.auth.login) You attempted to log in as account [hejinchi@cn.ibm.com] but the received credentials were for account [jinchihe@gmail.com].

Please check that your browser is logged in as account [hejinchi@cn.ibm.com] and that you are using the correct browser profile.
```

Seems only can logged in by google account (gmail is OK). That's not good ...

I created a question in the stackoverflow.com and add `gcloud` tag to ask...
https://stackoverflow.com/questions/57454772/cannot-login-gcloud-sdk-using-the-non-google-account

**Comment by jlewi** [comment]
@jinchihe Can you try opening a web browser in incognito mode and going to cloud.google.com and logging in using your IBM account?

**Comment by animeshsingh** [comment]
+1. Thanks @jinchihe for helping with this!

**Comment by jinchihe** [comment]
> @jinchihe Can you try opening a web browser in incognito mode and going to cloud.google.com and logging in using your IBM account?

Thanks @jlewi I tried to log in the `cloud.google.com` with IBM Email(hejinchi@cn.ibm.com), but after log in, the  Account shows google account `jinchihe@gmail.com`. 

And I got the reply from [stackoverflow.com](https://stackoverflow.com/questions/57454772/cannot-login-gcloud-sdk-using-the-non-google-account), seems we cannot log in using hird party domains by `gcloud`.
```
using third party domains (such a Hotmail, yahoo, etc) won't let you.
```

**Comment by jlewi** [comment]
@jinchihe In the interim if you want to send me a PR to add your gmail account you can go ahead and do that.

How did you link your IBM account to your gmail account and can you undo that? I could be wrong; the responder on SO probably knows more; but I thought you could create a Google account with a non-gmail account.

This [SO post](https://serverfault.com/questions/937135/whats-the-correct-way-of-having-a-gcp-account-without-a-gsuit-account) seems to confirm that.

In incognito mode what happens if you go to cloud.google.com click sign in and then create a new account and try to create an account with your IBM account?

**Comment by jinchihe** [comment]
@jlewi Thank you very much for your patient answer! But unlucky I still cannot create an account with IBM account. When I try to create a new account, by default gamil is needed, if I input IBM email, printed error message. pls see attachment. Thanks.
<img width="416" alt="图片" src="https://user-images.githubusercontent.com/13673199/63087112-f0052200-bf83-11e9-8316-ac23279137ba.png">

**Comment by jlewi** [comment]
@jinchihe That looks like the create gmail account window.

See screen shot below. In that case you can specif your **email** not a username. So I think you could use your ibm email.

I got to that window by doing

1. Go to https://cloud.google.com
1. Click sign-in
1. Click create account

![create_google_account](https://user-images.githubusercontent.com/777219/63123930-01880300-bf5f-11e9-9bfe-90ab4e81c992.png)

**Comment by jinchihe** [comment]
@jlewi  I remember feedback by Slack, maybe send wrong person.

I still cannot get access using IBM account. I guess that's need to refresh or do something after `internal-acls` merged?

```
(python3) hejinchidembp:kfserving hejinchi$ gcloud info |grep account
    account: [hejinchi@cn.ibm.com]
(python3) hejinchidembp:kfserving hejinchi$ gcloud --project=kubeflow-ci-deployment container clusters list
ERROR: (gcloud.container.clusters.list) ResponseError: code=403, message=Required "container.clusters.list" permission(s) for "projects/kubeflow-ci-deployment". See https://cloud.google.com/kubernetes-engine/docs/troubleshooting#gke_service_account_deleted for more info.
```
That's OK if login with my gmail account.
```
(python3) hejinchidembp:kfserving hejinchi$ gcloud info |grep account
    account: [jinchihe@gmail.com]
(python3) hejinchidembp:kfserving hejinchi$ gcloud --project=kubeflow-ci-deployment container clusters list
NAME            LOCATION    MASTER_VERSION  MASTER_IP        MACHINE_TYPE   NODE_VERSION    NUM_NODES  STATUS
...
```

**Comment by jinchihe** [comment]
@jlewi Yes, that works fine! Many thanks!

**Comment by jlewi** [comment]
Great!
