### ISSUE TITLE
[codelab-intro-mnist-feedback]:

### ISSUE THREAD

**Issue by wanglj-lanzer** [kubeflow/examples#607]
should be `go get sigs.k8s.io/kustomize/cmd/kustomize`

**Comment by jinchihe** [comment]
Explain more please? Your meaning is that installing kustomzie by this way? personally I think that's user choose, should not be fixation.

**Comment by wanglj-lanzer** [comment]
I mean for the instruction given in https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html#1

`go get sigs.k8s.io/kustomize`

will provide error information in GCP.  Otherwise, the above command can run successfully.

However, as the discussion in #609 , I recognize that the above command might install a wrong version, so it still does not work.  I will close this thread.  Thanks.
