### ISSUE TITLE
[codelab-intro-mnist-feedback]:secret

### ISSUE THREAD

**Issue by wanglj-lanzer** [kubeflow/examples#608]
> Kubeflow also added a Kubernetes secret called "user-gcp-sa" to our cluster,

but there is no output to when execute
`kubectl describe secret user-gcp-sa`

Meanwhile, there is no json file in the dir: /var/secrets/user-gcp-sa.json

Shall we need to create it by ourselves? If so, how?  Thank you

**Comment by jinchihe** [comment]
I guess that's caused the env problem, the document may help you, thanks.
https://www.kubeflow.org/docs/started/getting-started-gke/

**Comment by wanglj-lanzer** [comment]
Yes.  It seems need to create manually, but not mentioned by the introduction 

https://www.kubeflow.org/docs/gke/authentication/
