### ISSUE TITLE
Can't load the mnist traing data in the pod "mnist-train-local-worker*"

### ISSUE THREAD

**Issue by xauthulei** [kubeflow/examples#612]
Because when I try the example in `mnist` in my local cluster, I met this issue:
raceback (most recent call last):
 File “/opt/model.py”, line 233, in <module>
   tf.app.run()
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py”, line 126, in run
   _sys.exit(main(argv))
 File “/opt/model.py”, line 174, in main
   mnist = tf.contrib.learn.datasets.DATASETS[‘mnist’](args.tf_data_dir)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py”, line 250, in new_func
   return func(*args, **kwargs)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py”, line 300, in load_mnist
   return read_data_sets(train_dir)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py”, line 250, in new_func
   return func(*args, **kwargs)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py”, line 260, in read_data_sets
   source_url + TRAIN_IMAGES)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py”, line 250, in new_func
   return func(*args, **kwargs)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py”, line 219, in maybe_download
   temp_file_name, _ = urlretrieve_with_retry(source_url)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py”, line 250, in new_func
   return func(*args, **kwargs)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py”, line 172, in wrapped_fn
   return fn(*args, **kwargs)
 File “/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py”, line 200, in urlretrieve_with_retry
   return urllib.request.urlretrieve(url, filename)

My local cluster env are:
All of my cluster nodes are `On-premise`  behind the proxy, so I have added my proxy for the cluster nodes and  the docker engine. 

My Search results:
 we need to add the proxy to POD, Am I right ?

**Comment by xauthulei** [comment]
My temp solutions :
1> add the proxy to following patch files: 
~/llhu/examples-master/mnist/training/local# grep proxy *
Chief_patch.yaml:    name: https_proxy
Chief_patch.yaml:    value: $(https_proxy)
Chief_patch.yaml:    name: http_proxy
Chief_patch.yaml:    value: $(http_proxy)
Chief_patch.yaml:    name: no_proxy
Chief_patch.yaml:    value: $(no_proxy)
kustomization.yaml:    fieldPath: data.https_proxy
kustomization.yaml:  name: https_proxy
kustomization.yaml:    fieldPath: data.http_proxy
kustomization.yaml:  name: http_proxy
kustomization.yaml:    fieldPath: data.no_proxy
kustomization.yaml:  name: no_proxy
Ps_patch.yaml:    name: https_proxy
Ps_patch.yaml:    value: $(https_proxy)
Ps_patch.yaml:    name: http_proxy
Ps_patch.yaml:    value: $(http_proxy)
Ps_patch.yaml:    name: no_proxy
Ps_patch.yaml:    value: $(no_proxy)
Worker_patch.yaml:    name: https_proxy
Worker_patch.yaml:    value: $(https_proxy)
Worker_patch.yaml:    name: http_proxy
Worker_patch.yaml:    value: $(http_proxy)
Worker_patch.yaml:    name: no_proxy
Worker_patch.yaml:    value: $(no_proxy)
2> execute following CMDs:
kustomize edit add configmap mnist-map-training --from-literal=https_proxy=http://XXXXXX
kustomize edit add configmap mnist-map-training --from-literal=http_proxy=http://XXXXXX
kustomize edit add configmap mnist-map-training --from-literal=no_proxy=mycluster.icp,localhost,127.0.0.1

**Comment by xauthulei** [comment]
I wish to commit a PR to trace this, Could I get some suggestions ? many thanks

**Comment by jinchihe** [comment]
Seems that's caused your evn cannot connect network so just download source files by proxy.  Thank you putting the work around solution. but I think most of user env no need to set the proxy. Personally if we added the proxy_http, that may break normal user case. Agree? @xauthulei

**Comment by xauthulei** [comment]
@jinchihe , Thanks for your review comments. I initially introduce this issue aim to leave a record here for others checking.  In order to don't affect current one, we could introduce a "local_proxy" dir (same to current local)or we could clarify it in the readme , it may be save others efforts here.
