### ISSUE TITLE
Can not get kustomize installed on gcp console [codelab-intro-mnist-feedback]:

### ISSUE THREAD

**Issue by tmreic** [kubeflow/examples#613]
Can't get this command to work. go get sigs.k8s.io/kustomize i get the following error in gcp console. 

can't load package: package sigs.k8s.io/kustomize: no Go files in /home/tmreic/gopath/src/sigs.k8s.io/kustomize

i did try the the other methods to install kustomize and it appeared to install correctly but when i get to the step to use kustomize i can access the command.

when i run this step.
kustomize edit add configmap mnist-map-training \
    --from-literal=name=my-train-1

i get following error
-bash: kustomize: command not found

**Comment by jinchihe** [comment]
You can download binary from here https://github.com/kubernetes-sigs/kustomize/releases/tag/v2.0.3
