### ISSUE TITLE
E2E/CI  test for xgboost_synthetic

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#620]
We'd like CI for xgboost_synthetic notebook so we can ensure its working against the latest release.

This is becoming our go to quick start example so it would be great to have tests.

Related to #457 

/cc @jinchihe

**Comment by jinchihe** [comment]
@jlewi Yes,  totally agree with you. but we may waiting for fews days since the CI/CD is been changing now, we can use new framework for this.

**Comment by jlewi** [comment]
Thanks @jinchihe. The immediate changes to the CI/CD system are adding support for using a py_func to construct the Argo workflow defining the E2E test. That's almost ready to go; see kubeflow/testing#451

So we could begin defining the python steps and a py function to create a suitable workflow.

If someone had cycles we could probably start working on that. I had previously written this doc.
http://bit.ly/kf_example_testing_guide

I think the E2E test for xgboost_synthetic should be even simpler then what I wrote in that design doc because we don't need to build any docker images. I think we just need a 1 step workflow to run the notebook.

So the initial step is probably just parameterizing the notebook; e.g. with papermill so that we could easily run the notebook E2E using papermill and verify it runs to completion.

**Comment by jinchihe** [comment]
@jlewi OK, I will do this once get chance. Thanks.

/assign
