### ISSUE TITLE
[codelab-intro-mnist-feedback]:

### ISSUE THREAD

**Issue by spinelsun** [kubeflow/examples#622]
> no matches for OriginalId kubeflow.org_v1beta2_TFJob|~X|$(trainingName);
> no matches for CurrentId kubeflow.org_v1beta2_TFJob|~X|$(trainingName);
> failed to find unique target for patch kubeflow.org_v1beta2_TFJob|$(trainingName)

This error shows when trying to build the kustomization.yaml during the code lab under the training section.

**Comment by jinchihe** [comment]
pls use kustomize 2.0.3, new kustomize has bug here, see more in https://github.com/kubeflow/examples/issues/609
