### ISSUE TITLE
Example for local kubernetes server, local PostgreSQL database

### ISSUE THREAD

**Issue by ispmarin** [kubeflow/examples#627]
Hi all,

I´m trying to deploy Kubeflow on my own kubernetes installation and use it to get data from my own PosgreSQL database, to train a model using sklearn. So far I´m unable to find an example on how to do it, as all examples seems to get data either from CSV files or object stores, and use Tensorflow data structures instead of database cursors or pandas dataframes. Is there an example for a locally deployed kubeflow with data from databases and sklearn models?

**Comment by ispmarin** [comment]
Any ideas on how to connect to a PostgreSQL database and use sklearn?

**Comment by flacombe** [comment]
Hi

I second the question of @ispmarin as I look forward to have the same kind of kubeflow usage.
Is it wrong to do so?
