### ISSUE TITLE
404 for  job_mnist_DDP_GPU.yaml url

### ISSUE THREAD

**Issue by xiaoluwwwxiaolu** [kubeflow/examples#632]
hi,when I read the passage "Distributed training using Estimator" ,the url of "job_mnist_DDP_GPU.yaml " can not be opened.

https://github.com/kubeflow/examples/blob/master/pytorch_mnist/training/ddp/mnist/gpu/v1beta1/job_mnist_DDP_GPU.yaml

**Comment by jinchihe** [comment]
That has been removed from master, you can visit here https://github.com/kubeflow/examples/blob/v0.5.1/pytorch_mnist/training/ddp/mnist/gpu/v1alpha2/job_mnist_DDP_GPU.yaml

**Comment by xiaoluwwwxiaolu** [comment]
ok，thanks.

**Comment by xiaoluwwwxiaolu** [comment]
> That has been removed from master, you can visit here https://github.com/kubeflow/examples/blob/v0.5.1/pytorch_mnist/training/ddp/mnist/gpu/v1alpha2/job_mnist_DDP_GPU.yaml

thanks!
