### ISSUE TITLE
Update Google Codelabs to Kubeflow 1.0

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#641]
Opening this issue to track updating the codelabs to Kubeflow 1.0 as part of the Kubefow 1.0 release

Right now I see three codelabs
https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html?index=..%2F..index#0
https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis/#0
https://codelabs.developers.google.com/codelabs/cloud-kubeflow-pipelines-gis/index.html?index=..%2F..index#4

/cc @amygdala

**Comment by amygdala** [comment]
Just a note that the 3rd (pipelines) one is in progress re KF0.6; the others need a look.

**Comment by amygdala** [comment]
As per the PR above, one of the tests for the non-pipelines GH summarization example has succumbed to bitrot (unrelated to the PR) and was temp removed.  We'll want to investigate and fix.

**Comment by amygdala** [comment]
nooooo

**Comment by jlewi** [comment]
P0 for 1.0.

**Comment by jlewi** [comment]
/lifecycle frozen

@amygdala any update on this?

**Comment by amygdala** [comment]
cc @velascoluis, who is helping with this. He made an (internal) spreadsheet to record progress.

Just to note that
https://github.com/kubeflow/examples/blob/master/pipelines/mnist-pipelines/mnist_pipeline.py looks to be broken (in 0.7 too, I believe, given the nature of the probs).
(I didn't write this example; don't know much about the details of how it works.  Will see if I can suss it out though.  Unfortunately it's a highlighted docs example so we can't just mark it as broken).

cc @sarahmaddox

**Comment by amygdala** [comment]
Just to note that
https://github.com/kubeflow/examples/blob/master/pipelines/mnist-pipelines/mnist_pipeline.py looks to be broken --in 0.7 too, I believe, given the nature of the probs.

(I didn't write this example; don't know much about the details of how it works.  Will see if I can suss it out though.  Unfortunately it's a highlighted docs example so we can't just mark it as broken).

**Comment by amygdala** [comment]
I've asked @velascoluis if he can test the first 2:
https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html?index=..%2F..index#0
https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis/#0

I'll check the 3rd one.  (I've already confirmed that the code for this lab runs okay in 1.0).

**Comment by jlewi** [comment]
@amygdala @velascoluis any update?

**Comment by amygdala** [comment]
We're going to pull the e2e-gis codelab for now -- I asked Dan S on a separate internal bug if he had permissions to do that.  I'll follow up this a.m.  Then we should mark the example in the repo accordingly.  I'll put a PR for that. 
Apparently the issue that breaks it is ksonnet-related (don't know details), so probably straightforward to fix if we find a new owner, but it needs updating overall anyway.

**Comment by amygdala** [comment]
We should create a new codelab for your new mnist notebook.

**Comment by amygdala** [comment]
Update on the intro lab: via Luis, it has these issues:
"The cluster deploy steps relies on the UI, I did use my already existing cluster.The job submit fails at first with "tf-operator  Error creating: pods "my-train-1-chief-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found", this is easily fixable with the workaround @ https://www.kubeflow.org/docs/notebooks/troubleshoot/ , however I think this should be included as a step in the codelab. Then it fails again as this default editor KSA is not correctly binded with the GSA with the right permissions on the bucket (see pastebin). I did the binding t and it worked. TL.DR: The whole codelabs needs to be updated to get rid of the pre0.7 auth method from inside the pod ( mounting secret volume), other than that it works ok."

**Comment by amygdala** [comment]
For the e2e gis one: For now we're in the process of 'hiding' this codelab from the codelab index, and have also marked the text 'deprecated' for those who had the link bookmarked.  
We should similarly mark the readme in kf/examples -- I'll put in a PR for that shortly.

**Comment by amygdala** [comment]
I think I'll just swap in a new codelab that uses Jeremy's new notebook, for the intro one (https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html?index=..%2F..index#0)
