### ISSUE TITLE
Invalid slack link

### ISSUE THREAD

**Issue by hackintoshrao** [kubeflow/examples#650]
The slack link at the bottom of the [Readme.md](https://github.com/kubeflow/examples/blob/master/README.md#get-involved) is invalid. Could you point it to a valid community channel link?

<img width="1177" alt="Screenshot 2019-10-03 at 3 50 34 AM" src="https://user-images.githubusercontent.com/2609511/66086319-4dcfe680-e591-11e9-8948-b247e8a8fd9c.png">

**Comment by janeman98** [comment]
The slack link works well for me. 
@hackintoshrao, do you still experience problem?

**Comment by abhiverma1924** [comment]
@hackintoshrao invite link working fine, I have checked twice.
