### ISSUE TITLE
Update xgboost_synthetic to 0.7 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#655]
In 0.7 we will use workload identity.

As such notebooks should no longer need to use/set GOOGLE_APPLICATION_CREDENTIALS

The notebook
https://github.com/kubeflow/examples/blob/master/xgboost_synthetic/build-train-deploy.ipynb

Is currently checking GOOGLE_APPLICATION_CREDENTIALS we will need to update that code to work with workload identity.

P0 because this is part of our demo script for 0.7.

**Comment by kunmingg** [comment]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-f41f69f16d32> in <module>
----> 1 model = ModelServe(model_file="mockup-model.dat")
      2 model.train()

<ipython-input-4-77007601abb2> in __init__(self, model_file)
     17         self.model = None
     18         self._workspace = None
---> 19         self.exec = self.create_execution()
     20 
     21     def train(self):

<ipython-input-4-77007601abb2> in create_execution(self)
     88 
     89     def create_execution(self):
---> 90         r = metadata.Run(
     91             workspace=self.workspace,
     92             name="xgboost-synthetic-faring-run" + datetime.utcnow().isoformat("T"),

NameError: name 'metadata' is not defined

**Comment by krishnadurai** [comment]
Just another point to note:
I was testing with Istio 1.3.1 and ran into an issue installing the python package retrying (Step 2) saying the user does not have permissions to install it.

A workaround was to install with `pip3 install retrying --user` option first and then `pip3 install retrying`

**Comment by jlewi** [comment]
kubeflow/examples#676  should hopefully fix the test

There is however one more issue with model deployment kubeflow/examples#673
