### ISSUE TITLE
[GH Issue] Use Pachyderm to launch TFJobs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#67]
See kubeflow/kubeflow#151

We'd like to provide an example of Pachyderm + TFJob to illustrate

- Combining Pachyderm's orchestration capabilities with TFJob for distributed training
- Highlighting Pachyderm's data provenance features with TFJob

The current thought see kubeflow/kubeflow#151 is to create a simple Pachyderm pipeline to launch a TFJob to train the model.

The main challenge is that the data needs to be exported from Pachyderm and the resulting model imported into Pachyderm.

There's lots of discussion in kubeflow/kubeflow#151 about how to do this. The basic idea is 
- Pachyderm invokes a script that launches a TFJob
- As part of the TFJob we export/import data from the Pachyderm data store

    - A variety of ideas have been suggested; e.g. using an Argo workflow, init containers, sidecars etc...

To use Pachyderm we would also need to deploy Pachyderm on K8s.

**Comment by texasmichelle** [comment]
Fixed in #522
