### ISSUE TITLE
Can't run the fairing example fairing/examples/prediction/xgboost-high-level-apis.ipynb

### ISSUE THREAD

**Issue by lalithvaka** [kubeflow/examples#671]
Environment 
AKS + Kubeflow 0.62
Image: gcr.io/kubeflow-images-public/tensorflow-2.0.0a-notebook-cpu:v0.5.5

Running the fairing/examples/prediction/xgboost-high-level-apis.ipynb notebook.
cell1: !pip install --user -r requirements.txt cell works with no errors
cell2: import argparse
import logging
import joblib
import sys
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from xgboost import XGBRegressor

cell 2 fails with 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-f4fb022290ca> in <module>
      1 import argparse
      2 import logging
----> 3 import joblib
      4 import sys
      5 import pandas as pd

ModuleNotFoundError: No module named 'joblib'

Wondering if the image type I picked with tensorflow 2.0 is the issue. Tried Tensorflow 1.13.1 as well which failed.
![image](https://user-images.githubusercontent.com/8292387/67530632-8fc1e900-f674-11e9-8e3c-c27c1522f766.png)

**Comment by jtfogarty** [comment]
/area example
priority p2
