### ISSUE TITLE
xgboost_synthetic in 0.7.0 model doesn't deploy

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#673]
With 0.7.0 and the xgboost_synthetic example the model doesn't get deployed. The model is crash looping with

```
kubectl -n kubeflow-jlewi logs fairing-deployer-mpcjk-598789949b-cqsts
Traceback (most recent call last):
  File "/opt/conda/bin/seldon-core-microservice", line 6, in <module>
    from seldon_core.microservice import main
  File "/opt/conda/lib/python3.6/site-packages/seldon_core/__init__.py", line 2, in <module>
    from .storage import Storage
  File "/opt/conda/lib/python3.6/site-packages/seldon_core/storage.py", line 25, in <module>
    from azure.storage.blob import BlockBlobService
ImportError: cannot import name 'BlockBlobService'
```

**Comment by suneeta-mall** [comment]
I ran into this .. the seldon code specifies https://github.com/SeldonIO/seldon-core/blob/master/python/requirements.txt#L19 `azure-storage-blob >= 2.0.1` and `azure-storage-blob 12.0.0` gets installed but seldon core actually need needs `azure-storage-blob==2.1.0` as in 12.XX the `BlockBlobService` is no longer present

**Comment by suneeta-mall** [comment]
see here https://github.com/SeldonIO/seldon-core/issues/1023

**Comment by jlewi** [comment]
I have some in progress changes on my branch:
https://github.com/jlewi/examples/tree/fix_xgboost3

I think this fixes the issues but I need to clean it up and submit a PR.
