### ISSUE TITLE
Update mnist tests so that we get good signal in periodic dashboards

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#677]
We need to update the E2E tests for the mnist example. The end goal should be that we get clear signal in our test grid for the periodic examples
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples&group-by-hierarchy-pattern=%5B%5Cw-%5D%2B

Here's a screen shot of the current dashboard
![dashboard](https://user-images.githubusercontent.com/777219/68325271-e8828000-007d-11ea-9579-671f9eb6d1f2.png)

There's a couple different problems

* There's only one test result being reported named [mnist-test-${TIMESTAMP}](https://storage.googleapis.com/kubernetes-jenkins/logs/kubeflow-periodic-examples/1192137923626012675/artifacts/junit_test_train.xml)

  * But there are actually 3 different tests that should be running
  * [tfjob_test.py](https://github.com/kubeflow/examples/blob/master/mnist/testing/tfjob_test.py)
  * [deploy_test.py](https://github.com/kubeflow/examples/blob/master/mnist/testing/deploy_test.py)
  * [predict_test.py](https://github.com/kubeflow/examples/blob/master/mnist/testing/predict_test.py)

* Every test run gets a unique name in test grid which makes it hard to see how its tracked over time.

Here are the changes I think we need to make

* Change [tfjob_test.py](https://github.com/kubeflow/examples/blob/master/mnist/testing/tfjob_test.py) to use pytest to support better reporting of test results
* Change [deploy_test.py](https://github.com/kubeflow/examples/blob/master/mnist/testing/deploy_test.py) change to use pytest 
* Replace the ksonnet workflow with the use of python to define the workflow

  * We could add it to the existing workflow for xgboost_synthetic [create_e2e_workflow.py](https://github.com/kubeflow/examples/blob/master/py/kubeflow/examples/create_e2e_workflow.py)

     * or create a new a workflow
* We should be using [get_kf_testing_cluster.py](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/get_kf_testing_cluster.py) to create a KUBECONFIG entry for the cluster the test should run on
    * The workflow  [create_e2e_workflow.py](https://github.com/kubeflow/examples/blob/master/py/kubeflow/examples/create_e2e_workflow.py) already has a step to do this.

* Need to get kustomize into the test worker image kubeflow/testing#373

@jinchihe any interest in helping out with this?

**Comment by jinchihe** [comment]
@jlewi OK, will do that after next week since I'm running on other track recent days :-)

**Comment by jinchihe** [comment]
Sorry, need push back the ticket more days, I still cannot free up from urgent roadmap work now...

**Comment by jlewi** [comment]
No problem. Thanks for the update
