### ISSUE TITLE
[codelab-intro-mnist-feedback]: - docker push fails in cloud shell

### ISSUE THREAD

**Issue by elvinzhusiyu** [kubeflow/examples#685]
Using the Cloud Shell, there is error when __docker push__:
```
error creating overlay mount to /var/lib/docker/overlay2/9ab5d15e2b0c30a125872bda63d1f5d0fc8cc55283e7b5232acd5668de4cd857/merged: device or resource busy
```
Suggested by the discussion in this thread:
https://github.com/docker/for-linux/issues/711

A simple fix should be:
create a new file at location:
```
/etc/docker/daemon.json
```
Add the following content:
```
{
    "max-concurrent-uploads": 1
}
```

I test it and it works for me

**Comment by jtfogarty** [comment]
/area/example mnist

**Comment by jlewi** [comment]
Looks like the original bug report includes a work around.

Moving forward I think we should update the example to provide a notebook that runs in Kubeflow.
