### ISSUE TITLE
[codelab-minikf-kale-feedback]:

### ISSUE THREAD

**Issue by andradron** [kubeflow/examples#691]
I get a mistake after executing minikf command in started terminal. During the starting Kubeflow pods loading freezes at 94 or 97 % (30-31 / 32 pods ). It continues more than 30 minutes. 
Instance parameters :
Machine type: n1-highmem-8 (8 vCPUs, 52 GB memory)
Boot disk: 100 GB
Data disk: 148 GB

**Comment by jbottum** [comment]
Hey Andradon - I would delete and re-install with the default disk sizes.   The installation should finish in 20-25 minutes.
