### ISSUE TITLE
[codelab-intro-mnist-feedback]:

### ISSUE THREAD

**Issue by vijaytrainer** [kubeflow/examples#696]
while running this command 

kustomize build . | kubectl apply -f -

it's failing to create the tfjob, because it's looking for a svc account default-editor. Not sure what is that for, I removed that thing from the yaml and tried... after that it says... the secret svc account is not having enough permissions.

tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request (HTTP response code 403, error code 0, error message ''), response '{
  "error": {
    "code": 403,
    "message": "mnist-deployment-vm@xxxxxxx.iam.gserviceaccount.com does not have storage.buckets.get access to mnist-deployment-xxxxxx.",
    "errors": [
      {
        "message": "mnist-deployment-vm@xxxxxx.iam.gserviceaccount.com does not have storage.buckets.get access to mnist-deployment-xxxxxx.",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}

**Comment by jlewi** [comment]
The mnist example is intended to run in a namespace associated with a Kubeflow profile.
The Kubeflow profile resource ensures the required service accounts e.g. "default-editor" exist in the namespace.

On GCP if you don't use those service accounts you'd have to manually setup permissions. This includes mapping the service accounts to a GCP service account using workload identity to get GCP credentials.
