### ISSUE TITLE
Setup a shared environment

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/examples#7]
Setup a k8s cluster & cloud project for use in creating examples.

Component of [Kubeflow #157](https://github.com/kubeflow/kubeflow/issues/157).

**Comment by texasmichelle** [comment]
@jlewi Did you say you had an idea about how to get this done?

**Comment by jlewi** [comment]
@ankushagarwal Created the project kubeflow-dev and a corresponding kubeflow deployment
dev.kubeflow.org.

Access is controlled by the google group
devrel-team@kubeflow.org

You should have access as do other devrel folks at Google.

I think we can mark this as fixed.

**Comment by texasmichelle** [comment]
Great! I can access the cluster & project. Thanks @ankushagarwal!

**Comment by kaoutar55** [comment]
can you share how you configured the shared kubeflow-dev environment and how you manage the credentials for multiple users?
