### ISSUE TITLE
Issue serving MNIST model

### ISSUE THREAD

**Issue by plaffitte** [kubeflow/examples#709]
Hi, I have successfully trained the mnist model using a K8s cluster and stored it on S3, all according to the tutorial. I am now trying to serve the model and access it through the web-ui provided in folder font, but it gives me an error:

`❗ Exception making request: <_Rendezvous of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "Name resolution failure" debug_error_string = "{"created":"@1577449578.258073269","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2706,"referenced_errors":[{"created":"@1577449578.258070399","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3035,"grpc_status":14}]}" >`

I have no idea what this error refers to and would appreciate any hints.
Thanks in advance

**Comment by jlewi** [comment]
I believe that is a gRPC error indicating a problem connecting to your server. My suggestion would be to verify that your model is deployed.

How are you connecting to your server? Are you using `kubectl port-forward` or something else?

**Comment by plaffitte** [comment]
@jlewi yes I am using `kubectl port-forward`.
I can see that the deployment and the service were created when running `kubectl get services` and `kubectl get deployments`. How else can I check that my model is deployed?

**Comment by plaffitte** [comment]
I'm not sure what has changed but I now see a new error now, which says:
`StatusCode.INVALID_ARGUMENT details = "input tensor alias not found in signature: x. Inputs expected to be in the set {input_image}.`
