### ISSUE TITLE
Add example using Github actions do deploy pipeline to Kubeflow

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/examples#711]
The goal with this issue is to add an example on how to build and deploy pipelines to Kubeflow using GitHub actions.  This would help in using github actions for CI/CD for kubeflow for ML pipelines.

**Comment by NikeNano** [comment]
Lets continue the discussion here @hamelsmu. Feel free to chip in as well @inc0, @jlewi  mentioned that you had done some work on this before. 

I will update further with my thought in a separate comment later. 

@sarahmaddox  how do I add the correct labels to this Issue?

**Comment by hamelsmu** [comment]
Here are some resources that may be helpful:

Repo with links to a bunch of ML related GitHub actions - https://github.com/machine-learning-apps/actions-ml-cicd

End to end demo which includes deploying a pipeline to Argo: https://youtu.be/Ll50l3fsoYs

Do you want to get started on an Action and I can help review/troubleshoot?  Let me know how I can be of help!  Thanks for starting this!

cc: @aronchick

**Comment by sarahmaddox** [comment]
@NikeNano It looks like we need admin access to this repo, which I don't have. I'll ask someone to add the label. I see you've managed to add the issue to the [Doc Sprint Kanban board](https://github.com/orgs/kubeflow/projects/21), which is great!

**Comment by NikeNano** [comment]
Sounds great @hamelsmu! 

The current set up we use at work uses pure python commands which i run as part of a step in a github actions which also where my original thought. But I believe it makes more sense to make a "proper" github action for it. 

I will go through the material, the action-ml-cicd repo is great!

**Comment by NikeNano** [comment]
The planed work is the following: 
- Build the Kubeflow deployment action, as a container based GitHub action. I have a skeleton and hope to have it up and running soon. I will do this in a separate repo. Will tag you in it @hamelsmu. I intend to use the python kfp API, and allowing the user to pass in the path to the file and then compile and upload the pipeline. Could also add later the option to run it from the same action 
- Build a tutorial on how to use it and make a PR on this to Kubeflow Piplines sample as part of the Doc sprint.

**Comment by hamelsmu** [comment]
Sounds exciting!  Let us know if you get stuck on anything!

**Comment by NikeNano** [comment]
I have start the work on this some time back and most should be done, I have to update the doc a bit and will then align with @hamelsmu.  https://github.com/NikeNano/kubeflow-github-action

**Comment by sarahmaddox** [comment]
Thanks @NikeNano!

/assign @NikeNano

**Comment by hamelsmu** [comment]
This is excellent.  

cc: @aronchick @jlewi @t-holland @inc0 @awmatheson

**Comment by NikeNano** [comment]
The action is now up and running. Is there anyone from the kubeflow community that could also help review it? Which is the best place in the repo to add an example @sarahmaddox ?

**Comment by sarahmaddox** [comment]
/cc @amygdala 
/cc @joeliedtke 

This looks great @NikeNano!

I suggestion that the code would fit in well here:
https://github.com/kubeflow/examples/tree/master/pipelines
But I'll leave it to @amygdala for the final word.

For the docs, @joeliedtke is the lead tech writer on pipelines. I think there are two options, depending on the amount of time you have available.
* For a quick solution, you can add a link to the example from this page: https://www.kubeflow.org/docs/pipelines/tutorials/cloud-tutorials/
* For a longer project, it'd be great if you could write a tutorial that walks people through the solution, explaining how it uses GitHub Actions.

**Comment by NikeNano** [comment]
Cool! Then I will make a tutorial for it and make a PR.

**Comment by NikeNano** [comment]
Since this is done and merge I will close this issue. Thanks for the help everyone!

**Comment by sarahmaddox** [comment]
Thanks @NikeNano !
