### ISSUE TITLE
Simple Notebook Pipeline

### ISSUE THREAD

**Issue by fengpinghu** [kubeflow/examples#722]
The simple notebook pipeline failed on my onprem kubeflow setup:

The logs of the failed container is 

  File "<string>", line 4
    add(a: float, b: float) -> float:
         ^
SyntaxError: invalid syntax

It looks the container is passed the following command. Is it something that caused def keyword to be missing(when kfp does the func to container) thus the error above? 

    Command:
      python3
      -u
      -c
      name='add_op',
      description='adds two numbers',
      base_image=BASE_IMAGE  # you can define the base image here, or when you build in the next step. 
      add(a: float, b: float) -> float:
      '''Calculates sum of two arguments'''
      print(a, '+', b, '=', a + b)
      return a + b
      
      import argparse
      _parser = argparse.ArgumentParser(prog='add_op', description='adds two numbers\n')
      _parser.add_argument("--a", dest="a", type=float, required=True, default=None)
      _parser.add_argument("--b", dest="b", type=float, required=True, default=None)
      _parser.add_argument("----output-paths", dest="_output_paths", type=str, nargs=1)
      _parsed_args = vars(_parser.parse_args())
      _output_files = _parsed_args.pop("_output_paths")
      
      _outputs = add(**_parsed_args)
      
      if not hasattr(_outputs, '__getitem__') or isinstance(_outputs, str):
          _outputs = [_outputs]
      
      from pathlib import Path
      for idx, filename in enumerate(_output_files):
          _output_path = Path(filename)
          _output_path.parent.mkdir(parents=True, exist_ok=True)
          _output_path.write_text(str(_outputs[idx]))

**Comment by JohanWork** [comment]
i just tried it, dose the problem still exists for you @fengpinghu ?

**Comment by keeyzar** [comment]
Problem still exists, but on a bare metal cluster
other example pipelines can be executed just fine (the provided examples in the pipeline web ui)

problem is fixed when kernel is restarted after running the first cell of the simple-pipelines example
(!python -m pip....)

this was not tried earlier, as the documentation above states, the kernel should be restarted, when upgrading.
I did not have the feeling that I did an upgrade, rather an install.
