### ISSUE TITLE
update mnist e2e example on AWS for KF 1.0 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#724]
There are a number of issues with the mnist example that need to be addressed for KF 1.0
https://github.com/kubeflow/examples/tree/master/mnist

1. The example is using Ambassador not ISTIO for routes to the UI and model
1. The training job needs to be updated to run in a profile created namespace in order to have
the required service accounts

     * See kubeflow/examples#713
1. With ISTIO the default RBAC rules will prevent the web UI from sending requests to the model server
    * We either need to create an appropriate ISTIO rbac authorization policy or just remove the ISTIO sidecar
1. There is a requirement to use an old version of kustomize kubeflow/examples#713

     * I think we should probably just remove kustomize
     * kustomize might be increasing code reuse for different versions (e.g. GCP vs. AWS) but it hurts the readability IMO
     * kustomize gets in the way of the YAML spec which is what we want to show/teach users just getting started with Kubeflow

On GCP the solution we've opted for is to create a notebook that runs the entire example

- Draft pull request kubeflow/examples#723

A notebook has the following advantages

- The user can just do "Run All" to run all the cells; eliminates a lot of copying and pasting
- We can more easily add E2E testing to verify the notebook runs E2E 
- We can use rich markdown to provide detailed explanations of what's happening
- We can eliminate kustomize and just use Python f style strings
- This allows us to show users the raw YAML while easily updating it programmatically for their
  specific use case
- Any complex or shared logic can be "hidden" in a python library that is imported

The purpose of this bug is to figure out what we want to do about AWS and S3. It would be nice to have a similar mnist E2E example for all Kubeflow distributions.

My recommendation would be that we have separate notebooks for different Kubeflow distributions/clouds. This will lead to some code duplication but I think it provides a better learning experience. If we have one uber notebook I think we will end up with a lot of "If you are on Cloud X then do Y" and I think that hurts users.

/cc @Jeffwan

**Comment by eterna2** [comment]
Can I suggest that our kustomize base manifest should be fully fleshed out with everything you need - i.e. you can deploy as is with kubectl to get kubeflow up and running.

Then use overlays to overwrite and do the parameterization?

This way a non-kustomize user can still deploy as is with kubectl, while advanced users can continue using their own overlays?

**Comment by jlewi** [comment]
@Jeffwan do you think you will be able to pick this up?

**Comment by Jeffwan** [comment]
@jlewi working on this now.

**Comment by Jeffwan** [comment]
@eterna2 

I agree advanced users can continue using their own overlays. This would be supper helpful in real use case. For kubeflow/examples, it's unnecessary to use kustomizes. From maintain perspective, it's painful compare to notebook which can be easily tested.

I think the overall user experience is not good as Jupyter notebook. We assume most of the users running these examples are data scientist without experiences on Kubernetes. The most familiar stack for them are notebook and python.

**Comment by jlewi** [comment]
@Jeffwan I think we can close this right now that #740 is merged?

**Comment by Jeffwan** [comment]
PR has been merged.

/close
