### ISSUE TITLE
Update mnist E2E example for on prem vanilla KF

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#725]
There are a number of issues with the mnist example that need to be addressed for KF 1.0
https://github.com/kubeflow/examples/tree/master/mnist

1. The example is using Ambassador not ISTIO for routes to the UI and model
1. The training job needs to be updated to run in a profile created namespace in order to have
the required service accounts

     * See kubeflow/examples#713
1. With ISTIO the default RBAC rules will prevent the web UI from sending requests to the model server
    * We either need to create an appropriate ISTIO rbac authorization policy or just remove the ISTIO sidecar
1. There is a requirement to use an old version of kustomize kubeflow/examples#713

     * I think we should probably just remove kustomize
     * kustomize might be increasing code reuse for different versions (e.g. GCP vs. AWS) but it hurts the readability IMO
     * kustomize gets in the way of the YAML spec which is what we want to show/teach users just getting started with Kubeflow

In addition the vanilla/on prem/non-cloud specific distribution of Kubeflow has an added question of what to do about storage? The current solution uses a PV which works but isn't compatible with distributed training.

On GCP the solution we've opted for is to create a notebook that runs the entire example

- Draft pull request kubeflow/examples#723

A notebook has the following advantages

- The user can just do "Run All" to run all the cells; eliminates a lot of copying and pasting
- We can more easily add E2E testing to verify the notebook runs E2E 
- We can use rich markdown to provide detailed explanations of what's happening
- We can eliminate kustomize and just use Python f style strings
- This allows us to show users the raw YAML while easily updating it programmatically for their
  specific use case
- Any complex or shared logic can be "hidden" in a python library that is imported

The purpose of this bug is to figure out what we want to do about mnist for the  on prem distribution (e.g. kfctl_k8s_istio.yaml). It would be nice to have a similar mnist E2E example for all Kubeflow distributions.

My recommendation would be that we have separate notebooks for different Kubeflow distributions/clouds. This will lead to some code duplication but I think it provides a better learning experience. If we have one uber notebook I think we will end up with a lot of "If you are on Cloud X then do Y" and I think that hurts users.

In particular, if this version of the  example uses a PVC the YAML specs start to look different from Cloud solutions using object storage. I think putting all the variants into one notebook will be confusing.

/cc @krishnadurai @yanniszark

**Comment by jlewi** [comment]
Could we reuse the minio instance that KFP ships?

**Comment by swiftdiaries** [comment]
Looks like you can use it.
```python
!pip install minio
from minio import Minio
from minio.error import ResponseError

minioClient = Minio('cluster-service-endpoint',
                  access_key='accesskey',
                  secret_key='accesskeysecret',
                  secure=False)
```
The API Reference is here: https://docs.min.io/docs/python-client-api-reference

**Comment by jlewi** [comment]
@swiftdiaries Thanks; I think we will also need to update the K8s specs for 

* TFJob
* TFServing
* Tensorboard

to read from minio

/cc @mameshini

**Comment by swiftdiaries** [comment]
Yeah, I haven't gotten there yet.
I'll update here when I do

**Comment by mameshini** [comment]
+1 to having separate notebooks for different Kubeflow distributions/clouds. 

Currently, I am still working on the KF 1.0 upgrade and solving Istio/LB issues.  Once it's resolved, then I can use our on-prem environment to update MNIST notebook examples.

**Comment by jlewi** [comment]
@jinchihe @swiftdiaries is one of you working on this?

**Comment by swiftdiaries** [comment]
I'm working on this for vanilla-k8s

**Comment by jinchihe** [comment]
@jlewi I'm working for On-prem cluster for the mnist, will send a PR for this later. Thanks.

**Comment by swiftdiaries** [comment]
@jinchihe I've made a PR #737 
Could you please review it? I'd love to work together on that

**Comment by jinchihe** [comment]
@swiftdiaries Yeah, your PR looks great!  but we have duplicated works :-(  I still create the PR #742  to show what I did, there are some difference,  let's discuss that when you have time. 

I did that using Fairing and KFServing as I described in #742 . Maybe good to check my example in Fairing repo if the example repo takes your commits. 

@jlewi Comments?
