### ISSUE TITLE
Create a distributed object detection training example 

### ISSUE THREAD

**Issue by ldcastell** [kubeflow/examples#73]

**Comment by jlewi** [comment]
@ldcastell Can you expand the CL description? Do you have model code in mind? Datasets?

@yixinshi @aronchick

**Comment by ldcastell** [comment]
The goal is to demonstrate how to use kubeflow tooling (tf-operator and tf-job) to run a distributed object detection training job in an existing K8s cluster. The example will be based on the TensorFlow [Pets Tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md) using a dataset from: http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz and http://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz
