### ISSUE TITLE
Create an mnist E2E notebook for Azure

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#731]
For 1.0 the core CUJ is build, train, deploy. 

In  kubeflow/examples#723

we've created a notebook that highlights this core CUJ.

We'd like to have variations of this notebook for all the different platforms/clouds on which Kubeflow is supported.

So we'd like to have a variant of this notebook that is suited for Azure.

That primarily means updating the notebook to use Azure blob store. Alternatively you could use minio running on the cluster but using Azure blob store would probably be better.

/cc @aronchick

**Comment by jlewi** [comment]
@aronchick know anyone who could pick this up?

**Comment by berndverst** [comment]
@jlewi I talked to @aronchick last week and finally picked this up yesterday 😄 

Thanks for reviewing #759
