### ISSUE TITLE
Need work around the kustomize issue for mnist example

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/examples#733]
From some issue in the repo, someone got the issue with the new kustomize, in fact the mnist example is made with `kustomize v2.0.3`, but in the newer kustomize, there is a bug https://github.com/kubernetes-sigs/kustomize/issues/1295, and still not fixed, that's better to work around the kustomize issue for mnist example to avoid new kubeflower get into the problem while running kubeflow mnist example.

**Comment by jlewi** [comment]
@jinchihe my suggestion is that we remove kustomize altogether and use notebooks to run the example. Then we can just use python f style string to parameterize the YAML config.

See kubeflow/examples#723

We have issues to create corresponding notebooks for the various platforms.
#731 azure
#725 onprem/vanilla K8s
#724 aws
kubeflow/examples#723 GCP

**Comment by jinchihe** [comment]
Sounds good! @jlewi
