### ISSUE TITLE
[codelab-intro-mnist-feedback]: Dockerfile.model in examples/mnist needs to be fixed

### ISSUE THREAD

**Issue by JIElite** [kubeflow/examples#738]
Issue: Dockerfile.model in examples/mnist needs to be fixed
Platform: Google Cloud Platform with Cloud Shell

According to "[Introduction to Kubeflow on Google Kubernetes Engine](https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html#2)", we can run the following command to run docker container:
`docker run -it $IMAGE_PATH`

However, I ran into this error message at 21:40(PST) on 2020/2/18:
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/usr/bin/python\": stat /u
sr/bin/python: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled

The content in Docker.model is:
```
#This container contains your model and any helper scripts specific to your model.
# When building the image inside mnist.ipynb the base docker image will be overwritten
FROM tensorflow/tensorflow:1.15.2-py3

ADD model.py /opt/model.py
RUN chmod +x /opt/model.py

ENTRYPOINT ["/usr/bin/python"]
CMD ["/opt/model.py"]
```

After changing the entrypoint to `ENTRYPOINT ["/usr/local/bin/python"]`, the `docker run` command properly.

Is this dockerfile still in progress? or just leave something that no mentioned in the document.

Best regards,
Eli

**Comment by millerdz** [comment]
Submitted PR #744 to fix this issue.
