### ISSUE TITLE
Periodic notebook tests are failing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#750]
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples
Looks like the tests started failing on 02/22

**Comment by gabrielwen** [comment]
cannot reproduce the issue - from the log it was because `unable to access 'https://github.com/kubeflow/examples.git/': Could not resolve host: github.com`

**Comment by jlewi** [comment]
It looks like the most recent change to requirements.txt
https://github.com/kubeflow/examples/pull/737
was before the test started failing.

All recent runs of the test are failures.
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples

The most recent run was 10:54 PST 02/24. So it hasn't run in almost 24 hours.

**Comment by jlewi** [comment]
It looks like the jobs are running but not showing up in testgrid.
https://prow.k8s.io/?type=periodic&job=kubeflow-periodic-examples

**Comment by jlewi** [comment]
@gabrielwen here are the logs from the most recent failure

It looks like the error is an issue with workload identity.

```
RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the
 Google Compute Enginemetadata service. Status: 500 Response:\nb'Could not recursively fetch uri\\n'", <google.auth.transport.requests._Response
 object at 0x7f059bae9ef0>)
```

It looks like this ran on cluster

```
gcloud container clusters get-credentials kf-v1-0220-674 --project=kubeflow-ci-deployment --zone=us-east1-c
```

Are all the pods on the machine having problems with workload identity? If we restart the node metadata servers does that fix the problem?

[pod.logs.txt](https://github.com/kubeflow/examples/files/4249534/pod.logs.txt)

**Comment by gabrielwen** [comment]
I tried running a [pod](https://pantheon.corp.google.com/kubernetes/statefulset/us-east1-c/kf-v1-0220-674/kubeflow-kf-ci-v1-user/testing-worker?project=kubeflow-ci-deployment&tab=details&duration=PT1H&pod_summary_list_tablesize=20&service_list_datatablesize=20) to see, but I can actually run until writing html file to GCS:
`Forbidden: 403 GET https://www.googleapis.com/storage/v1/b/kubeflow-ci-deployment?projection=noAcl: Primary: /namespaces/kubeflow-ci-deployment.svc.id.goog with additional claims does not have storage.buckets.get
 access to kubeflow-ci-deployment.`

when running gcloud auth list:
```
ACTIVE  ACCOUNT
*       kubeflow-ci-deployment.svc.id.goog
```

**Comment by jlewi** [comment]
@gabrielwen what exactly did you do? The 403 error is an IAM permission error. The activated account kubeflow-ci-deploy.svc.id.goog doesn't look correct. It doesn't look like a GCP service account. 

I think the K8s job running papermill should be using workload identity to run as the user service account provisioned as part of Kubeflow deployment.

So I would expect the account to be something like

```
${KFAPP}-user@${PROJECT}.iam.gserviceaccount.com
```
How did you launch the pod? Did you set the K8s service account for the pod.

Looking at testgrid
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples

The notebooks running against the cluster deployed from master have started passing but the v1 cluster tests are still failing.

@gabrielwen did you run on master or v1?

Looking at
https://kf-ci-v1.endpoints.kubeflow-ci.cloud.goog/auto_deploy/

```

Version | Deployment Name | Age(HH:MM:SS) | Manifests Commit | kfctl version | gcloud command
-- | -- | -- | -- | -- | --
master | kf-master-0225-d7b | 0:06:14.413949 | f7e0947 | kfctl-v1-0-rc-2-13-g521fcfe | gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-east1-c kf-master-0225-d7b
master | kf-master-0225-5a8 | 5:13:54.109812 | a95de6b | kfctl-v1-0-rc-2-13-g521fcfe | gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-east1-c kf-master-0225-5a8
v1 | kf-v1-0220-674 | 4 days, 23:28:36.720194 | 2a9816f | kfctl-v1-0-rc-2-13-g521fcfe | gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-east1-c kf-v1-0220-674
unknown | kf-vmaster-0212-bde | 13 days, 19:50:14.553067 |   |   | gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-central1-a kf-vmaster-0212-bde
```

So the master cluster appears to be fresh whereas the v1 cluster appears to be about 4 days old.

**Comment by jlewi** [comment]
@gabrielwen I tried to log into the v1 cluster kf-v1-0220-674
https://kf-v1-0220-674.endpoints.kubeflow-ci-deployment.cloud.goog/ I get a DNS error
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by gabrielwen** [comment]
> @gabrielwen what exactly did you do? The 403 error is an IAM permission error. The activated account kubeflow-ci-deploy.svc.id.goog doesn't look correct. It doesn't look like a GCP service account.
> 
> I think the K8s job running papermill should be using workload identity to run as the user service account provisioned as part of Kubeflow deployment.
> 
> So I would expect the account to be something like
> 
> ```
> ${KFAPP}-user@${PROJECT}.iam.gserviceaccount.com
> ```
> 
> How did you launch the pod? Did you set the K8s service account for the pod.
> 
> Looking at testgrid
> https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples
> 
> The notebooks running against the cluster deployed from master have started passing but the v1 cluster tests are still failing.
> 
> @gabrielwen did you run on master or v1?
> 
> Looking at
> https://kf-ci-v1.endpoints.kubeflow-ci.cloud.goog/auto_deploy/
> 
> ```
> 
> Version | Deployment Name | Age(HH:MM:SS) | Manifests Commit | kfctl version | gcloud command
> -- | -- | -- | -- | -- | --
> master | kf-master-0225-d7b | 0:06:14.413949 | f7e0947 | kfctl-v1-0-rc-2-13-g521fcfe | gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-east1-c kf-master-0225-d7b
> master | kf-master-0225-5a8 | 5:13:54.109812 | a95de6b | kfctl-v1-0-rc-2-13-g521fcfe | gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-east1-c kf-master-0225-5a8
> v1 | kf-v1-0220-674 | 4 days, 23:28:36.720194 | 2a9816f | kfctl-v1-0-rc-2-13-g521fcfe | gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-east1-c kf-v1-0220-674
> unknown | kf-vmaster-0212-bde | 13 days, 19:50:14.553067 |   |   | gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-central1-a kf-vmaster-0212-bde
> ```
> 
> So the master cluster appears to be fresh whereas the v1 cluster appears to be about 4 days old.

I wrote a simple yaml and `kubectl apply` to bring up the worker, it's on kf-v1

**Comment by gabrielwen** [comment]
> @gabrielwen I tried to log into the v1 cluster kf-v1-0220-674
> https://kf-v1-0220-674.endpoints.kubeflow-ci-deployment.cloud.goog/ I get a DNS error
> DNS_PROBE_FINISHED_NXDOMAIN

it appears istio-ingressgateway was not healthy.  I tried to respawn (delete the pod and let the deployment spawn a new one) both istio-ingressgateway and istio-pilot but they are not able to heal themselves.

**Comment by gabrielwen** [comment]
@jlewi ok I think we have at least 3 problems:
- somehow istio doesn't work properly after the cluster was created for 2 days.
- metadata service is constantly failing.  I'm not sure how to restart the service, could you give me some pointers?
- checkout container in mnist test isn't able to connect to outside world, not even google.com

**Comment by jlewi** [comment]
@gabrielwen What does unhealthy mean? Are the pods being scheduled? Are the health checks failing? What do the logs show?

* If ISTIO is unhealthy that could potentially affect outbound access is a pod is running with an ISTIO side car
* I think we can ignore the metadata unhealthy issue for now (it could be a symptom of the same problem).
* Is it only the mnist pod that isn't able to connect to the outside world? If you run `kubectl run -it` and start some pod are you able to connect to the outside world?

**Comment by jlewi** [comment]
Its possible the DNS error is an issue with the ingress setup. Its possible this is unrelated to the outbound internet access issue. One possibility is that some of the resources were garbage collected as part of the cleanup script. You could follow the troubeshooting guide to debug
https://www.kubeflow.org/docs/gke/troubleshooting-gke/

I would suggest by trying to reproduce the outbound internat access problem using kubectl run to start a shell in a container.

**Comment by gabrielwen** [comment]
> @gabrielwen What does unhealthy mean? Are the pods being scheduled? Are the health checks failing? What do the logs show?
> 
> * If ISTIO is unhealthy that could potentially affect outbound access is a pod is running with an ISTIO side car
> * I think we can ignore the metadata unhealthy issue for now (it could be a symptom of the same problem).
> * Is it only the mnist pod that isn't able to connect to the outside world? If you run `kubectl run -it` and start some pod are you able to connect to the outside world?

- health check shows unhealthy.
- yap, only the mnist pod isn't able to connect, xgboost pod works fine.  the testing-worker that I started works fine as well.

**Comment by jlewi** [comment]
It looks like a new cluster got autodeployed and the tests are now passing.

A possible next step might be to add a mechanism to freeze auto-deployments; e.g. by adding some label. So that we can keep one of the deployments up for a long time to see if we can reproduce. 

I suspect the problem might be something is getting GC'd.

**Comment by jlewi** [comment]
Lets close this as not reproducible for now.
