### ISSUE TITLE
Update pets example to work with KF 1.0 and use a notebook

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#757]
The pets example needs to be updated to work with KF 1.0.
https://github.com/kubeflow/examples/tree/master/object_detection

It looks like it is still using ksonnet.

I think we should follow the example of mnist and create a notebook that 

1. Provides an E2E tutorial that walks people through the example
1. Can be run as a continuous integration test.

Here's the mnist notebook
https://github.com/kubeflow/examples/blob/master/mnist/mnist_gcp.ipynb

**Comment by jlewi** [comment]
Is there a version of Pets detection that uses Keras and TF 2.0? 

One of the GSOC summer of code ideas was to create an example using Keras and TF 2.0.

**Comment by Aakash1822** [comment]
Interested to work on this issue @jlewi

**Comment by jlewi** [comment]
@Aakash1822 great do you need anything in order to get started? If you are interested in doing this as part of GSOC; my suggestion would be to start drafting a proposal focusing on

1. What are the deliverables?
1. How you will go about delivering them?

**Comment by Aakash1822** [comment]
Okay sir @jlewi I will start with the same

**Comment by alok-raj** [comment]
@jlewi interested to work on this issue. Tell me the files where changes are required

**Comment by abhiverma1924** [comment]
@jlewi I have proposed another project idea for Gsoc, but to get familiar with the code structure I want to solve this issue before the GSoC period starts. I have gone through the python files in the **serving_script** folder and observed that it does not follow tensorflow 2.0 keras. Now in order to contribute and to write code in 2.0 version, I need some guidance or discussion to start working on the coding part.

**Comment by jlewi** [comment]
@abhiverma1924 Do you have a more specific question?

@alok-raj files are linked to in the PR title? Do you have a more specific question?

**Comment by abhiverma1924** [comment]
I want to convert the model code from tensorflow v1.0 to tensorflow v2.0. Up to what extent we can change the code and if we changed the model code, then what are other dependent files we need to take care of.

**Comment by jlewi** [comment]
@abhiverma1924 I think you are welcome to delete/edit/create all files in examples/object_detection.

I think the best thing to do would be to create an example notebook similar to mnist that runs through the entire example. Ideally you would add a test similar to the mnist test that would run through the notebook and verify it works.

**Comment by abhiverma1924** [comment]
@jlewi ok I understand, will work on it and get back to you soon. but please can you provide some gcp credits for those who had applied for GSoC it would be really helpful being a student.

**Comment by jlewi** [comment]
If your project is accepted to GSOC  we will provide you the resources you need to be successful. Unfortunately, I don't have credits to give out before then. So your options are

1. Wait and see if your project is accepted 
2. Work locally so you don't need GCP
3. Pay for GCP or use the GCP 300 free credits.

**Comment by abhiverma1924** [comment]
@jlewi, No issue I am working it, I have created the model  for the mnist using tensorflow v2.0 and mnist fashion dataset rather than simple mnist digit. Need a few more days to test the model and will update you soon.
