### ISSUE TITLE
[GH Issue] Scale out preprocessing using Apache Beam 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#76]
In the original [blog post](https://towardsdatascience.com/how-to-create-data-products-that-are-magical-using-sequence-to-sequence-models-703f86a231f8), Hamel filtered down the number of issues from 5M to 2M.

Can we use Apache Beam to run the preprocessing on all 5 million issues and scale out horizontally?

This would be the first step in giving us a very nice scaling out story.

**Comment by texasmichelle** [comment]
Anyone still interested in adding this feature?
