### ISSUE TITLE
[codelab-intro-mnist-feedback]: zone not specified in docs

### ISSUE THREAD

**Issue by eykanal** [kubeflow/examples#765]
The text is apparently taken wholesale from a workshop run at KubeCon '18. In "2. Set up the environment", section "Set your GCP project ID and cluster name", where the zone should be indicated the text says "We'll indicate which zone to use at the workshop.". This should probably be corrected to help the user figure out the zone they're using.

**Comment by kurianbenoy** [comment]
@eykanal can you specify in exactly which notebook of MNIST you faced this issue?

**Comment by eykanal** [comment]
https://codelabs.developers.google.com/codelabs/cloud-kubeflow-pipelines-gis/#2

The "report a mistake" link at the bottom left of that screen sent me here, hence the report.
