### ISSUE TITLE
No sample for notebook to Kubeflow deployment using Tensorflow 2.0 Keras

### ISSUE THREAD

**Issue by jamessandy** [kubeflow/examples#773]
With the release of tensorflow 2.0 keras, they should be a notebook demoing how to get started with it, and should also highlight how to tune hyperparameters, develop the model with TF serving and also setup continuous integration and continuous development also.

**Comment by alok-raj** [comment]
started working on this

**Comment by cfregly** [comment]
I would love to see a full KF pipeline example of this.  Hopefully, that’s in the works @alok-raj ?

**Comment by jamessandy** [comment]
hello @alok-raj i'm also working on the issue, that's why i opened it in the first instance
