### ISSUE TITLE
[GH Example] Surface RPC metrics

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#79]
It would be great to be able to show how we collect/surface RPC metrics for models.

The current thinking is to use ISTIO; see kubeflow/kubeflow#464

@lluunn Once we have ISTIO working 

/cc @lluunn

**Comment by lluunn** [comment]
Istio is running.
Do port-forwarding: kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=grafana -o jsonpath='{.items[0].metadata.name}') 3000:3000 

And then visit http://localhost:3000/dashboard/db/istio-dashboard

![screenshot from 2018-04-11 16-55-55](https://user-images.githubusercontent.com/32310205/38649035-3f1c1726-3da9-11e8-8874-8abe6ceb883b.png)

The left-most graph is the qps. The green line I guess it's some kind of health check. The yellow one is the real traffic.

**Comment by jlewi** [comment]
This is great; what determines the labels for the traces? The names don't seem to correspond anything specific to our service.

**Comment by lluunn** [comment]
You mean the unknown?
That's because the source (the service that sends traffic to issue-summarization service) is not in istio mesh.

**Comment by lluunn** [comment]
The webapp now also have the istio sidecar.
The labels for the model will still be unknown because the traffic goes through ambassador, which can't be in istio mesh.

**Comment by lluunn** [comment]
The label for the "model deployment" is still unknown because the ui service sends request through ambassador. So the "source" is still ambassador, and hence unknown to istio.

Should we change the ui to send request directly to the model service?
@jlewi @ankushagarwal

**Comment by jlewi** [comment]
Yes. The UI is in cluster there's no reason to use the reverse proxy; it can just use the K8s service directly for the model service.

**Comment by lluunn** [comment]
Working now
![screenshot from 2018-04-18 13-28-52](https://user-images.githubusercontent.com/32310205/38956458-80a4e4c6-430c-11e8-8b45-83ebc13a134f.png)
