### ISSUE TITLE
MNIST demo produces No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/namespace'

### ISSUE THREAD

**Issue by matejaputic** [kubeflow/examples#793]
OK so I’m trying to get the MNIST demo up and running under kubeflow. 

First followed directions to install minikube here, since I’m running Kubernetes locally:

https://kubernetes.io/docs/tasks/tools/install-minikube/

Then started minikube:

`minikube start --driver=virtualbox`,

Then followed directions to install kubeflow here:

https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

That took a while to churn but it brought up kubeflow.
Then I checked out this git repo:

https://github.com/kubeflow/examples

and navigated to the mnist directory and followed directions here:

https://github.com/kubeflow/examples/tree/master/mnist#mnist-on-kubeflow-on-vanilla-k8s

But I’m stuck on this `setup docker credentials` part. It tells me to create a base64 hash of USER:PASSWORD and throw it in a `config.json` file. I’m not sure what user or password to use here. I tried a random pair, but that didn’t work. When I run mnist_vanilla_k8s.ipynb, at some point it tells me 

```
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/namespace'
```

It makes sense that it can’t find something related to `secrets` because I haven’t set up any credentials anywhere. The instructions here

https://github.com/GoogleContainerTools/kaniko#pushing-to-docker-hub

are not helpful in this regard, because I’m still not sure where `USER` and `PASSWORD` should come from. 

Any ideas on how to proceed?

**Comment by sachua** [comment]
Hi, from my understanding, the example uses kaniko to build an image with the model, then pushes it to a docker registry for TFJob to pull from and train.

If you see step 2, DOCKER_REGISTRY = "ciscoai", you should replace ciscoai with your registry url. (docker hub, gcr.io, etc)
If you do not have an account, I would suggest using microk8s, as microk8s comes with a built-in insecure registry that you can use as your docker registry.

If you are using the microk8s built-in registry then your `config.json` should be
```json
{
  "insecure-registries" : ["localhost:32000"]
}
```

I also found https://github.com/kubeflow/examples/issues/748 very useful to help me successfully run the example.

Hope I was able to help!

**Comment by matejaputic** [comment]
@sachua Thank you!

**Comment by Rustastra** [comment]
I am facing the same issue running the notebook in Google-AI hub. Has anyone resolved it?

**Comment by Rustastra** [comment]
I think my issue was that I was following a [wrong](https://codelabs.developers.google.com/codelabs/cloud-kubeflow-pipelines-gis/index.html?index=..%2F..index#1) tutorial for the set-up :( 
now I'm following https://www.kubeflow.org/docs/gke/deploy/ and I hope it will get resolved
