### ISSUE TITLE
[codelab-minikf-kale-feedback]: ReadWriteMany not supported for standard Persisted Volumes

### ISSUE THREAD

**Issue by llimboy** [kubeflow/examples#798]
Apologies if have overlooked an existing issue ticket elsewhere - then please close.
Just wanted to bring attention to two issues with this codelab.
It's outdated in terms of the screenshots, which doesn't match current Kubeflow version and secondly a more servere issue related to ReadWriteMany functionality on persisted volumes that is expected for the kubeflow experiments pipeline but not supported on GKE standard volumes. 
It therefore fails on deploy.

One addition: Perhaps the tutorial documentation could be expanded with a small section outlining how to use a GCP Filestore instans as a persistent volume for the deployment.

**Comment by jbottum** [comment]
@vkoukis Hey Vangelis - Does the MiniKF team have someone to look at this?

**Comment by jbottum** [comment]
@llimboy Hi Llimboy, could you please provide a use case for RWX?  MiniKF is single node system, are you expecting to have multiple users on a single MiniKF

**Comment by llimboy** [comment]
Apologies, my bad, I see now that this not relevant for miniKF, but pertains to Kubeflow running in GKE on Google Cloud, which i was doing.
Will close this ticket.
