### ISSUE TITLE
Unable to access minio UI deployed with kubeflow.

### ISSUE THREAD

**Issue by lokeshjain279** [kubeflow/examples#799]
Hi All, I am having issue accessing minio UI deployed along with kubeflow using istio. I did port-forwarding but that didn't work. Tried adding external IP as well but nothing seems to work. I am wondering if anyone has faced this or know any workaround? I need to access minio UI to browse artifacts. 

```
kubectl get svc -n kubeflow | grep minio
minio-service                                  ClusterIP   10.100.199.84    172.19.16.217   9000/TCP            18d
```

**Comment by pengyuan** [comment]
I find this works:
kubectl port-forward svc/minio-service -n kubeflow 8081:9000 --address=0.0.0.0
then visit remotely: http://<ip>:8081
