### ISSUE TITLE
[codelab-pipelines-gis-feedback]:

### ISSUE THREAD

**Issue by rs9899** [kubeflow/examples#800]
Reports `Unsupported kubeflow version`  on page 3 when deploying kubeflow from https://deploy.kubeflow.cloud

All the steps previous to this was followed as in https://codelabs.developers.google.com/codelabs/cloud-kubeflow-pipelines-gis/?_ga=2.190031275.-1249852803.1588702117#2

Thanks

**Comment by jlewi** [comment]
@rs9899 Could you elaborate please? What reports "unsupported version"? Is this an error returned by click to deploy? I'm unclear whether this is referring to a version of GKE or Kubeflow?

**Comment by rs9899** [comment]
Sorry, but even I was unclear about it. It just pops as a dialogue box and that's it. Nothing is deployed. I had a report option there which resulted in an issue to this repo. 

Apart from this I don't know much about it.

**Comment by 8bitmp3** [comment]
Hi @jlewi If support for the UI (`deploy.kubeflow.cloud`) is deprecated, should we update the docs [here](https://www.kubeflow.org/docs/gke/deploy/deploy-ui/):

```
Follow these steps to open the deployment UI and deploy Kubeflow on GCP:
1. Open https://deploy.kubeflow.cloud/ in your web browser. You should see a form like the one in the above screenshot.
```

I understand that on Google Cloud you go to **AI Platform** > **Pipelines**, which takes you **Kubeflow Pipelines**. Then you configure it by creating a GKE cluster and deploy the pipelines. I can assist with updating the docs.

**Comment by jlewi** [comment]
The marketplace deployment only deploys KFP nothing else in KF. So if the example is using other applications in KF that won't work.

We should probably update the docs to use the CLI.

/cc @amygdala

**Comment by amygdala** [comment]
Yes, the codelab does need to be updated to use the CLI now.

I think the example should mostly work on standalone GKE KFP aside from:
 -  the istio routing for the 'web app' that is deployed wouldn't work.  Perhaps port-forwarding to that service would work instead.
 - the notebook section would need to be overhauled (to use AI Platform Notebooks instead)

So, it might be worth creating two new variants of the example, one for KFP on AI Platform, and the other for KF with CLI installation.  I'll put this on my stack :), hopefully should get to it pretty soon.

**Comment by 8bitmp3** [comment]
Thanks for the clarification on standalone KFP in GCP Marketplace @jlewi. 

When testing AI Pipelines using the UI, I am more keen to use the Cloud Shell on GCP. To use the full KF version you run `kfctl apply -V -f {... kubeflow/... /v1.0-branch/..gcp...yaml}`. Happy to see there's a separate "lighter" KF Pipelines v0.5.1 [here](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/) we can configure with `kfctlapply -V -f {... kubeflow/pipelines/.../kustomize/cluster-scoped-resources...}`. 

@amygdala if you're open to collaborate on updating the `github_issue_summarization` example, let me know. I've created a few tutorials based on GCP before (including with GKE and Istio mesh setups).

Thanks everyone 👍

**Comment by amygdala** [comment]
/reopen

https://github.com/kubeflow/examples/pull/823
