### ISSUE TITLE
mnist example broken in 1.1; ImportError: cannot import name 'V1alpha2TensorRTSpec'

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#806]
/kind bug

**What steps did you take and what happened:**

Running the [mnist example](https://github.com/kubeflow/examples/blob/master/mnist/mnist_gcp.ipynb) on a 1.1 cluster on GCP

Results in an import error

```
 from kfserving import V1alpha2TensorRTSpec
ImportError: cannot import name 'V1alpha2TensorRTSpec'
```

I believe the notebook is installing KFServing by installing fairing
https://github.com/kubeflow/examples/blob/10b34b8dc82daa7b0f9b61985d3171b58497e3b4/mnist/requirements.txt#L2

It looks like the example is pointing at a fairly old version of fairing 
https://github.com/kubeflow/fairing/commit/6717b3d3806c8093adf1186bc819ad887238f287  (from April as opposed to the 1.0 release)

So I suspect we might just need to upgrade fairing to 1.0

/cc @jinchihe

**Comment by jlewi** [comment]
Running

```
pip install --user --force git+git://github.com/kubeflow/fairing.git@v1.0.0
```

Didn't appear to fix the problem.

Running 

``` 
pip install --user --force kfserving
```

Did appear to fix it.

**Comment by jlewi** [comment]
I take that back. I was trying to `import kfservign` which is not the problem; the problem is

```
from kfserving import V1alpha2TensorRTSpec
```

**Comment by jlewi** [comment]
This class is defined here:
https://github.com/kubeflow/kfserving/blob/49eae18d669222cc6f923f7185c8000c17464f4c/python/kfserving/kfserving/models/v1alpha2_tensor_rt_spec.py#L36

It should be imported into the package here
https://github.com/kubeflow/kfserving/blob/49eae18d669222cc6f923f7185c8000c17464f4c/python/kfserving/kfserving/__init__.py#L51

My kfserving package appears to be outdated:

```
ls -la /home/jovyan/.local/lib/python3.6/site-packages/kfserving/models/
total 240
drwxr-sr-x 3 jovyan 1337  4096 Jul  6 13:42 .
drwxr-sr-x 8 jovyan 1337  4096 Jul  6 13:42 ..
-rw-r--r-- 1 jovyan 1337  2704 Jul  6 13:42 __init__.py
-rw-r--r-- 1 jovyan 1337  3639 Jul  6 13:42 knative_addressable.py
-rw-r--r-- 1 jovyan 1337  8686 Jul  6 13:42 knative_condition.py
-rw-r--r-- 1 jovyan 1337 10209 Jul  6 13:42 knative_url.py
-rw-r--r-- 1 jovyan 1337  3672 Jul  6 13:42 knative_volatile_time.py
-rw-r--r-- 1 jovyan 1337  5291 Jul  6 13:42 net_url_userinfo.py
drwxr-sr-x 2 jovyan 1337  4096 Jul  6 13:42 __pycache__
-rw-r--r-- 1 jovyan 1337  7532 Jul  6 13:42 v1alpha2_alibi_explainer_spec.py
-rw-r--r-- 1 jovyan 1337  5406 Jul  6 13:42 v1alpha2_batcher.py
-rw-r--r-- 1 jovyan 1337  3840 Jul  6 13:42 v1alpha2_custom_spec.py
-rw-r--r-- 1 jovyan 1337  9135 Jul  6 13:42 v1alpha2_deployment_spec.py
-rw-r--r-- 1 jovyan 1337  6407 Jul  6 13:42 v1alpha2_endpoint_spec.py
-rw-r--r-- 1 jovyan 1337 10894 Jul  6 13:42 v1alpha2_explainer_spec.py
-rw-r--r-- 1 jovyan 1337  7337 Jul  6 13:42 v1alpha2_inference_service_list.py
-rw-r--r-- 1 jovyan 1337  8023 Jul  6 13:42 v1alpha2_inference_service.py
-rw-r--r-- 1 jovyan 1337  6241 Jul  6 13:42 v1alpha2_inference_service_spec.py
-rw-r--r-- 1 jovyan 1337 10877 Jul  6 13:42 v1alpha2_inference_service_status.py
-rw-r--r-- 1 jovyan 1337  4309 Jul  6 13:42 v1alpha2_logger.py
-rw-r--r-- 1 jovyan 1337  5862 Jul  6 13:42 v1alpha2_onnx_spec.py
-rw-r--r-- 1 jovyan 1337 15762 Jul  6 13:42 v1alpha2_predictor_spec.py
-rw-r--r-- 1 jovyan 1337  6901 Jul  6 13:42 v1alpha2_py_torch_spec.py
-rw-r--r-- 1 jovyan 1337  5910 Jul  6 13:42 v1alpha2_sk_learn_spec.py
-rw-r--r-- 1 jovyan 1337  5282 Jul  6 13:42 v1alpha2_status_configuration_spec.py
-rw-r--r-- 1 jovyan 1337  5960 Jul  6 13:42 v1alpha2_tensorflow_spec.py
-rw-r--r-- 1 jovyan 1337 10061 Jul  6 13:42 v1alpha2_transformer_spec.py
-rw-r--r-- 1 jovyan 1337  5894 Jul  6 13:42 v1alpha2_triton_spec.py
-rw-r--r-- 1 jovyan 1337  6697 Jul  6 13:42 v1alpha2_xg_boost_spec.py
-rw-r--r-- 1 jovyan 1337  2917 Jul  6 13:42 v1_time.py
```

It is missing tensorrt.

**Comment by jlewi** [comment]
```
 from kfserving import V1alpha2TensorRTSpec     
```
Is coming from fairing
~/.local/lib/python3.6/site-packages/kubeflow/fairing/deployers/kfserving/kfserving.py

**Comment by jlewi** [comment]
It looks like TensorRT was removed from KFServing
https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/__init__.py

@jinchihe it looks like the problem is that `V1alpha2TensorRTSpec` has been removed from KFServing but fairing is still trying to import it.

Is fairing using an older version of the KFServing library?

**Comment by jlewi** [comment]
https://github.com/kubeflow/fairing/blob/7c46973f49934f683dadefb43f85dcdaf2259586/requirements.txt#L3

Downgrading to 

```
kfserving==0.2.1.1
```

Fixed the problem. So it looks like the problem is that fairing isn't compatible with the 0.3 version of the KFServing library.

**Comment by jlewi** [comment]
kubeflow/examples#807 should fix the example by pinning to the older version of kfserving.
We might also need to update the fairing library to forward fix to be compatible with 0.3.0

**Comment by jinchihe** [comment]
Sorry I was off for personal urgent things. I'm going to take a look and fix that. Thanks @jlewi

**Comment by jinchihe** [comment]
Root cause: That caused by `Triton Renaming` (https://github.com/kubeflow/kfserving/pull/750) in KFServing, KFSeving SDK updated but the Fairing is not updated accordingly. In fact we should consider compatibility but KFServing do not get 1.0 release :-) Anyway, I will fix that from Fairing. Thanks.

**Comment by jinchihe** [comment]
I already fixed the problem in Fairing, and I will release new version V1.0.1 to fix this one once the another PR merged. Very soon (before or tomorrow). Thanks.

**Comment by jinchihe** [comment]
`kubeflow-fairing` v1.0.1 has been released, now we can try the case with new SDK. Thanks.
https://pypi.org/project/kubeflow-fairing/1.0.1/
