### ISSUE TITLE
Upgrade/Reenable notebook presubmits

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#809]
Notebook presubmits were disabled in #808 because they had become stale

* They were using Argo
* Notebook tests had been generalized to use Tekton and most of the code had moved to kubeflow/testing
* We need to upgrade the presubmits to use the blueprint clusters since we are no longer auto-deploying older instances of Kubeflow.

**Comment by jbottum** [comment]
@yanniszark Hey Yannis, any comments on this ?
