### ISSUE TITLE
[GH Example] Use katib/modeldb to store model results

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#81]
It looks like [kartib](https://github.com/kubeflow/hp-tuning) has some very nice features for keeping track of your models and then surfacing metrics for those models e.g. by launching TensorBoard.

It would be great to combine this with our GH issue summarization example. In particular it would be great if we could load the trained model in a DB and then use the kartib/model DB UI to browse models and look at results.

/cc @gaocegege @YujiOshima

**Comment by jlewi** [comment]
See kubeflow/hp-tuning#43

**Comment by jlewi** [comment]
See kubeflow/examples#134 experiments with ModelDB's API and UI

**Comment by texasmichelle** [comment]
Anyone still interested in pursuing this?
