### ISSUE TITLE
Fix the linear training mode in the mnist example, upstream to Tensorflow

### ISSUE THREAD

**Issue by elsonrodriguez** [kubeflow/examples#82]
I never got the Linear training mode working, so I stuck to CNN for the example.

https://github.com/kubeflow/examples/blob/1be7ccb1425131867a1efdbe6ed147201013813b/mnist/model.py#L142

If the Linear portion of the model were fixed, it could be upstreamed in tensorflow to replace their example and reduce duplication.

Also the upstream model does not support distributed training in its current form, or exporting.

**Comment by texasmichelle** [comment]
Anyone still interested in pursuing this?
