### ISSUE TITLE
Create Computer Vision Tenorflow & Opencv  Brain MRI Images for Brain Tumor Detection  kuebflow pipeline with KF serving

### ISSUE THREAD

**Issue by aniruddhachoudhury** [kubeflow/examples#826]
In this example will build an end to end pipeline for the given link [kaggle](https://www.kaggle.com/navoneel/brain-mri-images-for-brain-tumor-detection). It includes Batch Prediction and Single Prediction. And it also includes all the components Computer Vision with Tensorflow 2.3.0 and OpenCV. it also includes Visualisation in Kubeflow Pipeline like tensorboard ,ROC, confusion matrix.

**Comment by ShreyPandit** [comment]
@aniruddhachoudhury I would like to take up this problem. But can you guide me where can I refer/learn about kubeflow end to end deployment method, as I suppose that would be needed here.
Thanks

**Comment by adhilcodes** [comment]
I have made a solution for this . Can I create a PR
