### ISSUE TITLE
[codelab-minikf-kale-feedback]: Error on Compile and Run

### ISSUE THREAD

**Issue by rafaelnovello** [kubeflow/examples#834]
Hi guys!

On step 4 of From Notebook to Kubeflow Pipelines with MiniKF and Kale colab notebooks I got:

```
Message: 401 (Unauthorized) Error for 'GET http://rok.rok.svc.cluster.local/services/settings', API Error: unauthorized, code: 401, msg: Unauthorized, details: This server could not verify that you are authorized to access the document you requested
```

Follow the print 

<img width="1347" alt="Captura de Tela 2020-11-17 às 18 56 30" src="https://user-images.githubusercontent.com/423789/99455744-09271c00-2907-11eb-9288-438a23ac9200.png">

**Comment by rafaelnovello** [comment]
Hi @jbottum - It wan't resolved. I'm running on MiniKF and the storage is Rok. Could I help more?

**Comment by sam360digitmg** [comment]
@jbottum I am facin the same issue as well. Running the codelab using MiniKF on AWS.
