### ISSUE TITLE
Failed to install kfp in Notebook Server

### ISSUE THREAD

**Issue by brightlee6** [kubeflow/examples#838]
I followed this:
https://github.com/kubeflow/examples/blob/master/pipelines/simple-notebook-pipeline/Simple%20Notebook%20Pipeline.ipynb

But failed to install kfp with both images tensorflow-1.15.2-notebook-cpu:1.0.0 and tensorfolw-2.1.0-notebook-cpu:1.0.0. Seems I can solve this issue by unstall enum34, but need sudo permission for jovyan. Any idea how to solve this? Thanks a lot.

Attached error msg below.

![image](https://user-images.githubusercontent.com/6210065/103563994-9cde8880-4e72-11eb-96a0-7c3f96334655.png)

**Comment by PatrickGhosn** [comment]
You need to update pip and install with pip as user
!pip3 install --upgrade pip --user
!pip3 install kfp
