### ISSUE TITLE
Ownership for kubeflow/example?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/examples#845]
> I'm no longer actively involved in this repository. I'm not sure what the current ownership structure is.
> 
> It doesn't look like this repo is currently owned by a WG:
https://github.com/kubeflow/community/blob/master/wgs.yaml
> 
> Which suggests to me it might be orphaned.
cc @kubeflow/project-steering-group 
>
> I would suggest starting a thread on the mailing list to figure out which WG owns this repository and if no WG owns it what to do about it.

_Originally posted by @jlewi in https://github.com/kubeflow/examples/issues/843#issuecomment-766861816_

**Comment by Bobgy** [comment]
/cc @jinchihe 
Creating a separate issue to discuss this.

**Comment by DavidSpek** [comment]
Re-posting my thoughts from my [comment](https://github.com/kubeflow/examples/pull/843#issuecomment-766867353) on the PR:

It seems like some of the examples do contain OWNERS files. I think another route of action is that each example should belong to a WG, this way an example demonstrating serving would be owned by the serving WG. With this structure it would be possible to pull in the example folder from each upstream repo (such as pipelines or serving) and have them together in this repo, similar to how manifests works.
