### ISSUE TITLE
[GH Example] Friction points from Katacoda

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/examples#88]
Katacoda recently created a [scenario](https://www.katacoda.com/kubeflow) out of the GitHub issue summarization example and ran into a number of frustrating issues. The following items need to be addressed in order to turn this example into a platform-independent self-contained unit for use in a wide number of environments.

- [ ] @benhall to add his list

**Comment by jlewi** [comment]
Could we follow an approach similar to using a bootstrap container as being discussed in kubeflow/kubeflow#673

The idea is users would do something like
kubectl create -f http://github.com/kubeflow/examples/ghissue-bootstrap.yaml
kubectl exec -it gh-bootstrap /bin/bash
quickstart.sh

The goal is that quickstart.sh would set everything up and try to optimize things for their config. This gives them a shell they can drop into with all the tools/code they need.

Could Katacoda reuse these container images?

**Comment by jlewi** [comment]
Duplicate of #89
