### ISSUE TITLE
Katacoda scenario on github summarization example; friction log

### ISSUE THREAD

**Issue by lluunn** [kubeflow/examples#89]
Running through the [scenario](https://www.katacoda.com/kubeflow/scenarios/deploying-github-issue-summarization)

step 1: no issue

step2:
* **[Major issue]** Creating GCP token (secret) not working --> error: invalid literal source test, expected key=value
*   **[Major issue]** As a result, the tfjob failed to start: secrets "gcp-credentials" not found
* `git clone https://github.com/kubeflow/examples.git; cd
   examples/github_issue_summarization/notebooks/ks-app`
   This is not working. The app is at examples/github_issue_summarization/ks-kubeflow
* It's creating an environment called tfjob. I think the name should be changed.
  Using tfjob as an env name is confusing.
* Once an environment has been delayed --> typo ? s/delayed/created ?
* Points to IssueSummarization.py for the code. But training code should be training.py
* The image is currently gcr.io/agwl-kubeflow/tf-job-issue-summarization. We should use
   gcr.io/kubeflow-images-public
* The `kubectl log` command (very last one) needs `-nkubeflow`

step3: 
* Got `The environment has expired. Please refresh to get a new environment.` when started. So I 
   refresh, redo step 1, and go straight to step3.
* I was able to get the prediction back. But it took ~5min for the pod to be ready. We should probably 
  mention that (also how to check the status, `kubectl describe ...`.

step4:
* **[Major issue]** `ks apply frontendenv -c ui` failed because github_token is not set.
   Needs `ks param set ui github_token $GITHUB_TOKEN`

cc @jlewi @ankushagarwal

**Comment by BenHall** [comment]
Thanks for the feedback.

Step2: 
GCP: Thanks, we'll get the format updated however, we're reluctant to provide a live read/write access token to a storage bucket as it could be open for abuse. Ideally the example would support Kubernetes persistent volumes so users can decided where the data comes from. This would allow us to train a smaller subset to demonstrate the workflow. 

Updated the path, kubelog, typo and path. I don't think the repo existed when we created this so thank you for highlighting. 

Step 3: In terms of performance, we'll pre-cache the images once we are happy with which version to use. This will speed up the pod creation as at the moment the images need to be pulled.

Step 4: Thanks! We used `kubectl patch` to workaround this but pleased it's been added as a ksonnet parameter.

**Comment by jlewi** [comment]
Thanks Ben.

It would probably also be a good idea on the Katacode side specify a commit when cloning GitHub example so it doesn't break unexpectedly. e.g. #84 just moved the ksonnet app.

There are a couple issues on our end that I think need to be fixed

#90 Need to check in vendor directory.

Filed #91 to eliminate the use of GCS.

**Comment by BenHall** [comment]
@jlewi I'm just building a new environment. Which image should I be using for the training and serving? I see the following in the repo:
```
github-issue-summarization-serving-demo |  
issue-summarization |  
issue-summarization-model |  
issue-summarization-seldon |  
issue-summarization-ui |  
issue-summarization-ui-test
```

My guess is `issue-summarization-seldon` for serving, `issue-summarization-ui` for UI. Which image is `tf-job-issue-summarization` ?

**Comment by jlewi** [comment]
@BenHall What is image in this context? Docker image or ksonnet component?

@texasmichelle can probably answer better than me what the right component is.

**Comment by jlewi** [comment]
I think you will want the following docker images

* gcr.io/kubeflow-images-public/issue-summarization:0.1
* gcr.io/kubeflow-images-public/issue-summarization-ui@sha256:8344fcc0aa47c5923884e14141b91a2615ef765769f200c9974a48d876e78187

Can you explain how the docker images fit into your environment? Is this just to cache them for faster downloads? It looks like in step 2 you tell them to clone our example repository. So I'd expect the images used would be determined by the code in the example.

I just noticed that you are forking kubeflow/kubeflow and have users point to katacoda/kubeflow? Can you explain why you are doing this.

Is the scenario somewhere in GitHub that I can look at. I'd like to understand how this all works to see if there's anything we can do to make it easier to maintain.

For reference I'm basing my answer on what is running in our [dev instance](https://github.com/kubeflow/testing/blob/master/dev-kubeflow-org/ks-app/components/params.libsonnet).

/cc @texasmichelle

**Comment by BenHall** [comment]
We're seeing the liveness probe failing https://github.com/kubeflow/examples/issues/106

**Comment by jlewi** [comment]
Those are good reasons. My intent was only to learn how to better support Katacoda. I don't have a strong oppinion about where the scenarios should live.

**Comment by jlewi** [comment]
@BenHall The changes to support running on PVC are committed.I haven't had a chance yet to go through the complete example E2E yet to make sure it works yet.

/cc @texasmichelle

**Comment by BenHall** [comment]
Thanks @jlewi ! This looks to fix serving, is the plan to do the same for the training too?

**Comment by jlewi** [comment]
@BenHall Training is already done via #98.

So here's roughly how it should go

Training: 

1. Create a PVC to store the data

```
ks apply ${ENV} -c data-pvc
```
   * This will create a volume using default storage class

1. Download the data to the PVC via K8s job

```
ks apply ${ENV} -c data-downloader
```
1. Submit training job using the PVC

```
ks apply ${ENV} -c tfjob-pvc
```

Serving

1. Deploy the model

```
ks apply ${ENV} -c issue-summarization-model-serving
```
   * This will deploy a model baked into the container

1. (Optional) Deploy the webapp

```
ks apply ${ENV} -c ui
```
