### ISSUE TITLE
[GH Issue] Use persistent volumes for the data

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#91]
To support Katacoda kubeflow/examples#89 we should remove the need for GCP credentials.

1. For the output we should support using PD and making it easy for users to set the PD by parameters.
1. The input is trickier. I think GCS requires an account even for public buckets. If its a single file we could use the http URL to access it. 
 
    * My suggestion would be to create a script that would copy the data using curl to a PD. We could then  run that script as a K8s job.

**Comment by texasmichelle** [comment]
Anyone still interested in pursuing this? Is it still relevant?
