### ISSUE TITLE
Broken link to AWS instructions https://www.kubeflow.org/docs/aws/deploy/install-kubeflow

### ISSUE THREAD

**Issue by keypointt** [kubeflow/examples#942]
As in https://github.com/kubeflow/examples/tree/master/mnist#aws, this link for "Follow the [AWS instructions]" is not found https://www.kubeflow.org/docs/aws/deploy/install-kubeflow

> MNIST on Kubeflow on AWS
Follow these instructions to run the MNIST tutorial on AWS
Follow the [AWS instructions](https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/) to deploy Kubeflow on AWS

Potential fix:
* update link in example repo
* update the documentation of `docs` of kubeflow repo

Apologies if there is already an effort fixing it and I did miss it.
Thank you.

**Comment by js-ts** [comment]
@keypointt It would be great if you could create a PR to fix the issue

**Comment by keypointt** [comment]
A quick PR submitted https://github.com/kubeflow/examples/pull/948 , thanks :)

**Comment by keypointt** [comment]
PR already merged long time ago, closing this issue
